#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

declare_parcel_as_script_with_stdin <<'-/-'
Handling Gentoo overlays.

== Local Overlays ==

*Local overlays* (i.e., filesystem-based overlays specific to the current
system) may be added by manually editing `/etc/layman/layman.cfg`. Append an
entry to the `overlays` variable prefixed by `file:///` succeeded by the
absolute path to that overlay's `overlay.xml` file: e.g.,

.Local Overlays
==========================================
------------------------------------------
overlays  : http://www.gentoo.org/proj/en/overlays/repositories.xml
            http://gpo.zugaina.org/lst/gpo-repositories.xml
            file:///home/leycec/bash/raia-gentoo/overlay.xml
------------------------------------------
==========================================
-/-

#FIXME: Add support for Paludis' overlay management.

# ....................{ TESTERS                            }....................
#FIXME: Rename to is_gentoo_overlay_command_pathable().
declare_function_with_stdin <<'/---'
[status: boolean] is_gentoo_overlay_command_installed(void)

Return success if at least one command for managing overlays has been installed.
/---
function is_gentoo_overlay_command_installed() {
    is_pathable layman
}

# ....................{ PRINTERS                           }....................
declare_function_with_stdin <<'/---'
string print_gentoo_overlay(string overlay_name)

Print the passed currently added overlay. If such overlay has not yet been
added, an exception is thrown.
/---
function print_gentoo_overlay() {
    die_unless_arg 'expected one overlay name'
    die_unless_pathable layman
    layman --info="${1}"
}

declare_function_with_stdin <<'/---'
string print_gentoo_overlays(void)

Print all currently added overlays.
/---
function print_gentoo_overlays() {
    # Validate sanity.
    die_if_args
    die_unless_pathable layman

    # Print such overlays.
    {
        print_message_heading 'overlays added'
        layman --list-local

        output_newline
        print_message_heading 'overlays (all)'
        layman --list
    } | page_stdin
}

# ....................{ ADDERS                             }....................
declare_function_with_stdin <<'/---'
void add_gentoo_overlay(string overlay_name, integer priority = 50)

Add the passed overlay with the passed priority (defaulting to 50). If `ALL`,
add all addable overlays. By default, the global Portage tree has a priority
of -1000. Since higher priority overlays take precedence over lower priority
overlays, this implies overlays added with default precedence take precedence
over the global Portage tree -- usually (but not always) what you want.
/---
function add_gentoo_overlay() {
    die_unless_args_1_to_2 'expected one overlay name and optional priority'
    die_unless_pathable layman
    layman --fetch --add="${1}" --priority="${2:-50}"
}

# ....................{ REMOVERS                           }....................
declare_function_with_stdin <<'/---'
void remove_gentoo_overlay(string overlay_name)

Remove the passed overlay. If `ALL`, remove all currently added overlays.
/---
function remove_gentoo_overlay() {
    die_unless_arg 'expected one overlay name'
    die_unless_pathable layman
    layman --delete="${1}"
}

# ....................{ UPDATERS                           }....................
declare_function_with_stdin <<'/---'
void update_gentoo_overlay(string overlay_name)

Update the passed added overlay. If `ALL`, update all added overlays as under
update_gentoo_overlays().
/---
function update_gentoo_overlay() {
    die_unless_arg 'expected one overlay name'
    die_unless_pathable layman
    layman --sync="${1}"
}

declare_function_with_stdin <<'/---'
void update_gentoo_overlays(void)

Update all added overlays and the list of addable overlays.
/---
function update_gentoo_overlays() {
    # "layman" fails with non-zero status if at least one overlay fails to
    # update. Since this routinely occurs (e.g., if a remote overlay is
    # temporarily unavailable), ignore such failure.
    die_if_args
    die_unless_pathable layman
    layman --sync-all or ignore_failure
}

# --------------------( WASTELANDS                         )--------------------
#FUXME: Clumsy. Rename to is_gentoo_overlay_command().
#alias_cli_abbreviation {lay}man='layman'
#declare_function '
#string print_gentoo_overlays_all(void)
#
#Print all addable overlays (i.e., currently added or not).
#'
#function print_gentoo_overlays_all() {
#    die_if_args
#    run_code_paged layman --list
#}

# ....................{ UPDATERS ~ overlays                }....................
# void update_gentoo_overlays_if_possible(void)
#
# If at least one command for managing overlays has been installed, update all
# added overlays and the list of addable overlays.
#update_gentoo_overlays_if_possible() {
#    is_gentoo_overlay_command_installed and update_gentoo_overlays
#}
