#!/usr/bin/env zsh
# ====================[ linux                              ]====================
#                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy Linux. This Zeshy component implements Linux-specific functionality.

# ....................{ KERNEL                             }....................
# void _import_all_linux(void)
#
# Import all Zeshy dependencies relevant for the current Linux system. This
# means:
#
# * All scripts under "zeshy/distro" corresponding to the current distribution
#   (e.g., "zeshy/distro/exherbo" on Exherbo systems).
_import_all_linux() {
    local distro_script_path="${ZESHY_HOME}/zeshy/linux/distro/$(get_distro_name)"
    [[ -f "${distro_script_path}" ]] && import "${distro_script_path}"
}

# ....................{ KERNEL                             }....................
#FIXME: Implement! Should, in order:
#* Accept either an absolute or relative pathname. If absolute, is assumed to be
#  a "tar.bz2" archive having the kernel to be upgraded to; otherwise, to be the
#  basename of a directory under "/usr/src/". In the former case, transparently
#  unpack that archive into "/usr/src/", without overwriting any existing data.
#* Copy the "/usr/src/linux/.config" file, if present, into the new kernel dir.
#* Cd to the new kernel dir.
#* Run "make oldconfig".
#* If successful, forcefully overwrite the "/usr/src/linux" symlink.
#* Cd back.

# void upgrade_kernel(char *kernel_name)
#upgrade_kernel() {
#}

# ....................{ KERNEL                             }....................
_import_all_linux

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyleft 2007-2010 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
