#!/usr/bin/env zsh
# ====================[ zip                                ]====================
#                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy zip.

# ....................{ COMPRESSION                        }....................
# void zip_dir(char *dirname)
#
# Recursively zip the passed dirname into an archive having the same name but
# suffixed by ".zip" under the current directory.
zip_dir() {
    die_unless_one_argument 'expected exactly one dirname'
    string ZESHY_SCRIPT_NAME='zip_dir'
    archive_dir "${1}" zip\
        zip '-r' ''\
        unzip '-l' ''
}

# void zip_file(char *filename1, char *filename2, ...)
#
# Iteratively zip each passed filename into an archive having the same name but
# suffixed by ".zip" under the current directory.
zip_file() {
    die_unless_at_least_one_argument 'expected at least one filename'
    string ZESHY_SCRIPT_NAME='zip_file'
    while is_nonempty "${1}"; do
        archive_file "${1}" zip\
            zip '' ''\
            unzip '-l' ''
        shift
    done
}

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyright 2007-2012 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
