#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

declare_parcel_as_script_with_stdin <<'/---'
Handle core path aliases.
/---

# ....................{ CHANGES                            }....................
#FIXME: O.K.; the nomenclature is good, but defining such aliases will have to
#wait until we have a robust alias declarer for doing so, as :change_dir_start
#must accept an argument as follows:
#
#    :change_dir_start~{ "${new_dir}" }~
#    ...
#    :change_dir_stop

# declare_alias_with_stdin 'void :change_dir_start(void)'\
#     ':store_dir "${dirname__cds}"
#     :try {' <<'/---'
# Change...
# /---
# 
# declare_alias_with_stdin 'void ::change_dir_stop(void)'\
#     '} always ={
#         :restore_dir
#     }:' <<'/---'
# Restore...
# /---

# --------------------( WASTELANDS                         )--------------------
