#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2016 by Cecil Curry.
# See "LICENSE" for additional details.

:parcel <<'/---'
Handle *glob qualifiers* (i.e., `(#q`- and `)`-delimited expressions suffixing
path-specific globs).

== See Also ==

* Section ``Glob Qualifiers'' of `man zshexpn`, documenting these qualifiers.
* zy://*-root/path/qualifier.zy, a parcel handling path qualifiers _not_
  prefixed by path-specific globs and hence _not_ requiring the early-time
  compilation of function argument type `:str/:glob` required by this parcel.
/---

# ....................{ TESTERS                            }....................
#FIXME: Refactor to make the list of passed glob qualifiers optional. Revivify!

# Report success if at least one such path matches.
:func_ '[status=:bool] :path.is_^=(
    :str/:glob glob +:str glob_qualifiers)' :func{
    :list pathnames
    :set_list_to_glob_qualified_paths pathnames "${@}"
    :List.is_nonempty pathnames

#FIXME: Great example, but overlong. Split below.
}:func <<'/---'
Report success if at least one existing path matches both the passed glob _and_
all passed glob qualifiers.

== See Also ==

* :set_list_to_glob_qualified_paths().

== Examples ==

.:path.is_^=()
==========================================
[source]
------------------------------------------
>>> :str on_mondays=\
...    "Both Plato and Xenophon attribute to Socrates and obviously share with
...     him an awareness of the destructive effects of work on the worker as a
...     citizen and a human being. Herodotus identified contempt for work as an
...     attribute of the classical Greeks at the zenith of their culture. To
...     take only one Roman example, Cicero said that \"whoever gives his labor
...     for money sells himself and puts himself in the rank of slaves.\" His
...     candor is now rare, but contemporary primitive societies which we are
...     wont to look down upon have provided spokesmen who have enlightened
...     Western anthropologists. The Kapauku of West Irian, according to
...     Posposil, have a conception of balance in life and accordingly work only
...     every other day, the day of rest designed \"to regain the lost power and
...     health.\" Our ancestors, even as late as the eighteenth century when
...     they were far along the path to our present predicament, at least were
...     aware of what we have forgotten, the underside of industrialization.
...     Their religious devotion to \"St. Monday\" – thus establishing a de
...     facto five-day week 150-200 years before its legal consecration – was
...     the despair of the earliest factory owners. They took a long time in
...     submitting to the tyranny of the bell, predecessor of the time clock. In
...     fact it was necessary for a generation or two to replace adult males
...     with women accustomed to obedience and children who could be molded to
...     fit industrial needs. Even the exploited peasants of the ancient regime
...     wrested substantial time back from their landlord's work. According to
...     Lafargue, a fourth of the French peasants' calendar was devoted to
...     Sundays and holidays, and Chayanov's figures from villages in Czarist
...     Russia – hardly a progressive society – likewise show a fourth or fifth
...     of peasants' days devoted to repose. Controlling for productivity, we
...     are obviously far behind these backward societies. The exploited muzhiks
...     would wonder why any of us are working at all. So should we."
>>> :dir.make on_diversity
>>> :path.is_^= ?n_d?v?rs?t? '/^F' 'u'"$(get_user)" :and
...     get_string_line "${on_mondays}" -1
would wonder why any of us are working at all. So should we.
------------------------------------------
==========================================
/---

# ....................{ GETTERS                            }....................
#FIXME: Refactor into
#:set_string_to_glob_qualified_path_first_if_found().
:func_ '<globbable> [stdout = :str, status = :bool]
    get_path_globbed_matching_qualifier_first_if_found(
        :str glob,
        :str glob_qualifier1, ...)' :func{
    # If at least one pathname matches, get the first; else, fail. For
    # simplicity, implement such test as an "and" rather than "if" conditional.
    :list pathnames
    :set_list_to_glob_qualified_paths pathnames "${@}"
    :List.is_nonempty pathnames and :stdout.echo "${pathnames[1]}"
}:func <<'/---'
Get the first passed path that exists _and_ matches the passed glob and all
passed glob qualifiers or return failure if no such path exists. See
get_path_matching_qualifier_first_if_found() for further details: e.g.,

.get_path_globbed_matching_qualifier_first_if_found()
==========================================
[source]
------------------------------------------
>>> get_path_globbed_matching_qualifier_first_if_found /bin/mk[a-z]## rAR xEX
/bin/mkdir
------------------------------------------
==========================================

== Exception Handling ==

There exists no corresponding get_path_globbed_matching_qualifier_first(). While
implementing such function is certainly feasible, any exceptions thrown by such
implementation would be unlikely to be human-readable (e.g.,
`no path matches glob "'imprimi_potest/'*(#q'w/')"`). Instead, simply call this
function and throw an exception if such call fails: e.g.,

.get_path_globbed_matching_qualifier_first_if_found() Exception Handling
==========================================
[source]
------------------------------------------
>>> :str on_divinity=\
...    "Confronted, when the weather is fine and I am in propitious emotional
...     circumstances, with certain landscapes, certain works of art, certain
...     human beings, I know, for the time being, that God's in his heaven and
...     all's right with the world. On other occasions, skies and destiny being
...     inclement, I am no less immediately certain of the malignant
...     impersonality of an uncaring universe. Every human being has had similar
...     experiences. This being so, the sensible thing to do would be to accept
...     the facts and frame a metaphysic to fit them. But with that talent for
...     doing the wrong thing, that genius for perversity, so characteristically
...     human, men have preferred, especially in recent times, to take another
...     course. They have either denied the existence of these psychological
...     facts; or if they have admitted them, have done so only to condemn as
...     evil all such experiences as cannot be reconciled in a logical system
...     with whatever particular class of experiences they have chosen,
...     arbitrarily, to regard as \"true\" and morally valuable. Every man tries
...     to pretend that he is consistently one kind of person and does his best
...     consistently to worship one kind of God. And this despite the fact that
...     he experiences diversity and actually feels himself in contact with a
...     variety of divinities."
>>> get_path_globbed_matching_qualifier_first_if_found /etc/[a-z]##tab ^u0 or\
...     get_string_line "${on_worship}" 1
Confronted, when the weather is fine and I am in propitious emotional
------------------------------------------
==========================================
/---

# ....................{ SETTERS                            }....................
:func_ '<globbable> :void :set_list_to_glob_qualified_paths(
    :str:list? list_name,
    :str glob,
    :str glob_qualifier, ...)' :func{
    # Localize arguments.
    :str list_name__sltpgmq="${1}" glob__sltpgmq="${2}"
    :args.shift 2

    # Qualify such glob with such qualifiers.
    :qualify_glob glob__sltpgmq "${@}"

    # Perform such match.
#   :stdout.echo "glob: ${glob__sltpgmq}"
    set_list_to_evaluation "${list_name__sltpgmq}" '${~glob__sltpgmq}'
}:func <<'/---'
Set the passed list to the subset of passed paths that exist _and_ match both
the passed glob and all passed glob qualifiers: e.g.,

.:set_list_to_glob_qualified_paths()
==========================================
[source]
------------------------------------------
>>> :list pseudo_files
>>> :set_list_to_glob_qualified_paths pseudo_files /proc/[a-z]## -.L0
>>> :stdout.echo "${pseudo_files[1,3]}"
/proc/buddyinfo /proc/cgroups /proc/cmdline
------------------------------------------
==========================================

== Qualifier Syntax ==

For convenience, glob qualifiers may be formatted as any of the following:

* Undelimited strings (e.g., `^-U`, matching files _not_ owned by the current
  effective user after resolving symbolic links).
* `(`- and `)`-delimited strings (e.g., `(^-U)`).
* `(#q`- and `)`-delimited strings (e.g., `(#q^-U)`).
/---

# ....................{ QUALIFIERS                         }....................
:func_ ':void :qualify_glob(
    :str:str? glob_name,
    :str qualifier1, ...)' :func{
    # Localize arguments.
    :str glob_name__qg="${1}" glob_qualifiers__qg
    shift_arg

    # If only passed one such qualifier, suffix such string by such qualifier,
    # delimited by "(#q" and ")" if not already delimited by either "(" and ")"
    # *OR* "(#q" and ")". For efficiency and implementation differences between
    # this and the alternative case, implement such cases independently.
    if { is_arg } {
        glob_qualifiers__qg="${1}"
        :is "${glob_qualifiers__qg}" == '('(|'#q')*')' :si or
              glob_qualifiers__qg="(#q${glob_qualifiers__qg})"
    # Else, multiple qualifiers were passed. Iteratively suffix such string with
    # such qualifiers, delimited by "(#q" and ")" if not already.
    } else {
        # For efficiency, append onto a local string rather than calling
        # :suffix_string() each iteration.
        :str glob_qualifier__qg
        for     glob_qualifier__qg ("${@}") {
            # If such qualifier is unsafely delimited by "(" and ")", convert
            # "(" to "(#q". zsh requires each of a series of multiple qualifiers
            # to be prefixed by "(#q" rather than "(".
            if :is "${glob_qualifier__qg}" != '(#q'*')' :si {
                glob_qualifiers__qg+="(#q${${glob_qualifier__qg#(}%)})"
            } else {
                glob_qualifiers__qg+="${glob_qualifier__qg}"
            }
        }
    }

    # Suffix such glob by such qualifiers.
    :suffix_string "${glob_name__qg}" "${glob_qualifiers__qg}"
}:func <<'/---'
Append the first passed string with the concatenation of all remaining passed
strings converted to *glob qualifiers* (i.e., `(#q`- and `)`-delimited strings
to be appended to pathname globs, filtering undesirable pathnames from the set
of all pathnames matching such globs).

== Examples ==

.:qualify_glob()
==========================================
[source]
------------------------------------------
>>> :str glob='/etc/**/*.lisp'
>>> :qualify_glob glob '-.' 'u0'
>>> ::stdout.echo "${glob}"
/etc/**/*.lisp(#q-.)(#qu0)
>>> :list pathnames; pathnames=( ${~glob} )
>>> ::stdout.echo_newlined "${pathnames[@]}"
/etc/gentoo-init.lisp
/etc/lisp-config.lisp
------------------------------------------
==========================================
/---
