#!/usr/bin/env zsh
# ====================[ 7z                                 ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2014 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy 7-zip, handling the "7z" command's LZMA-derived compression format.

#FIXME: Not the best function names, really.
# ....................{ ENCRYPTION                         }....................
# void 7z_encrypt_path(string pathname)
#
# Encrypt (but do not compress) the passed directory as a 7-zip archive.
7z_encrypt_dir() {
    die_unless_args_0_to_1 'expected optional pathname'
    print_warning 'please consider a password of at least 17 characters, if security genuinely matters!'
    print_warning 'please note this command assumes media and hence performs no additional compression!'
    print_message 'if you require such compression, consider 7z_encrypt_compress_dir()'

    archive_path 7z\
        7z 'a -mhe=on -mx0 -p' ''\
        7z 'l' ''\
        "${@}" 
}

# void 7z_encrypt_compress_path(string pathname)
#
# Encrypt and compress the passed directory as a 7-zip archive.
7z_encrypt_compress_dir() {
    die_unless_args_0_to_1 'expected optional pathname'
    print_warning 'please consider a password of at least 17 characters, if security genuinely matters!'
    print_warning 'please note this command performs additional compression and hence consumes more time!'
    print_message 'if you do not require such compression, consider 7z_encrypt_dir()'

    archive_path 7z\
        7z 'a' '-mhe=on -p'\
        7z 'l' ''\
        "${@}" 
}

# --------------------( WASTELANDS                         )--------------------
#   die_unless_args_0_to_2\
#       'expected one source dirname to encrypt and one optional target filename to encrypt to'
#   string dirname="${1}"
#   string 7z_filename="${2:-dirname}"
