#!/usr/bin/env zsh
# ====================[ bchunk                             ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Handle Binchunker, a CLI for converting bin/cue to ISO files.

# ....................{ CONVERTERS                         }....................
# string convert_bin_cue_files_to_iso(string filename_sans_filetype)
#
# Convert the files with passed filename suffixed with ".bin" and ".cue" to a
# filename suffixed with ".iso".
function convert_bin_cue_files_to_iso() {
    # Validate passed arguments, forcefully removing passed filetypes from the
    # passed filename.
    die_unless_arg 'expected one filename'
    string filename_sans_filetype
    filename_sans_filetype="$(get_file_sans_file_type "${1}")"

    # Binchunk for great freedom. Since "bchunk" supplies a rather stellar
    # interface, there's really no need for pontificating. Just do it!
    bchunk\
        "${filename_sans_filetype}.bin"\
        "${filename_sans_filetype}.cue"\
        "${filename_sans_filetype}"
}

# --------------------( WASTELANDS                         )--------------------
