#!/usr/bin/env zsh
# ====================[ bzip2                              ]====================
#                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy bzip2, implementing "bzip2"-specific functionality.
#
# --------------------( TODO                               )--------------------
# * We should instead implement a new generalized head function working
#   transparently on all compressed files -- not simply bzip2-compressed files.
# * Ditto for bzcat(). In fact, the prior generalization requires a generalized
#   bzcat function as a dependency.

# ....................{ ALIASES                            }....................
#FIXME: Supplant options with "ZESHY_BZIP2_OPTIONS" and so on.
interactive_alias bzip2='bzip2 --keep --best'
interactive_alias bunzip2='bunzip2 --keep'
interactive_alias bzcat='run_paged bzcat'
interactive_alias bzhead='run_paged bunzip2_head'

# ....................{ DECOMPRESSION                      }....................
# string bunzip2_head(string filename, string head_option1, string head_option2, ...)
#
# Print the first portion of the passed bz2-compressed filename according to the
# passed "head" options, defaulting to the first 1,000 file lines if no such
# options are specified.
bunzip2_head() {
    die_unless_args 'expected at least a filename'

    # Localize and validate arguments.
    string bz2_file="${1}"
    shift_arg
    list head_options; head_options=( "${@}" )
    is_string_nonempty "${head_options[@]}" or head_options=( '-1000' )

    bzcat "${bz2_file}" | head "${head_options[@]}"
}

# ....................{ COMPRESSION                        }....................
# void bzip2_path(string pathname)
#
# Recursively bzip2 the passed pathname into an archive having the same name but
# suffixed by ".tar.bz2" under the current pathectory.
bzip2_path() {
    die_unless_arg 'expected one pathname'
    archive_path "${1}" tar.bz2\
        tar '-cjvf' ''\
        tar '-tjvf' ''
}

#FIXME: Obsolete.
# string bzcat_page(string bzcat_option1, string bzcat_option2, ...)
#
# Print the passed bz2-compressed filename under the current pager.
#bzcat_page() {
#    page bzcat "${@}"
#}

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyright 2007-2013 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
