#!/usr/bin/env zsh
# ====================[ driconf                            ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2015 by Cecil Curry.
# See "LICENSE" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Handle "driconf", a GUI for configuring the Direct Rendering Infrastructure
# (DRI) of the current OpenGL driver (e.g., Mesa Gallium).

# ....................{ CONFIGURERS                        }....................
# void configure_mesa_dri()
#
# Configure the current OpenGL driver's Direct Rendering Infrastructure (DRI).
function configure_mesa_dri() {
    die_if_args
    run_code_disowned driconf
}

# --------------------( WASTELANDS                         )--------------------
