#!/usr/bin/env zsh
# ====================[ mutt                               ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2012 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Handle "mutt", the popular CLI-based mail client.

# ....................{ ALIASES                            }....................
interactive_substitution {mu}tt='mutt -y'

# --------------------( WASTELANDS                         )--------------------
