#!/usr/bin/env zsh
# ====================[ ntpd                               ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy Network Time Protocol (NTP), synchronizing local system time against
# remote time servers.

# ....................{ PRINTERS                           }....................
# string print_ntpd(void)
#
# Print a status report on the currently running NTP daemon and hence the
# current progress of synchronizing local system time against remote time
# servers.
print_ntpd() {
    # Validate sanity.
    die_if_args
    die_unless_running ntpd

    # Status report.
    {
        say_first_section 'local NTP daemon'
        ntpq -c readvar
        say_next_section 'remote NTP peers'
        ntpq -p
        say_next_section 'time-related kernel variables'
        ntptime
    } | run_paged
}

# --------------------( WASTELANDS                         )--------------------
