#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2015 by Cecil Curry.
# See "LICENSE" for additional details.

:parcel <<'/---'
Handle `ntpd`, a CLI daemon utilizing the Network Time Protocol (NTP) to
synchronize local system time against remote time servers.
/---

# ....................{ PRINTERS                           }....................
declare_function_with_stdin <<'/---'
string :print_ntpd()

Print a human-readable synopsis of the currently running NTP daemon.
current status of synchronizing local system time with remote time servers.
/---
function :print_ntpd() {
    #FIXME: If "ntpd" isn't running, try to start it before simply dying.
    #Naturally, this suggests a new pair of start_service() and stop_service()
    #functions abstracting out responsibility for doing so, with appropriate
    #OS- and distro-specific implementations.

    # Validate sanity.
    die_if_args
    :die_unless_process ntpd

    # Print such synopsis.
    {
        print_message_heading 'Local NTP Daemon'
        command ntpq -c readvar

        print_message_heading 'Remote NTP Peers'
        command ntpq -p

        print_message_heading 'Time-related Kernel Variables'
        command ntptime
    } | page_stdin
}

# --------------------( WASTELANDS                         )--------------------
