#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2015 by Cecil Curry.
# See "LICENSE" for additional details.

:parcel <<'/---'
Handle networking devices.
/---

# --------------------( WASTELANDS                         )--------------------
#FUXME: "eth0" is no longer a sensible default device name. Simply drop the
#default, please.
