#!/usr/bin/env zsh
# ====================[ list                               ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2012 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy List, handling file and directory lists.

# ....................{ ALIASES                            }....................
interactive_alias ls='list_path_concisely'
interactive_alias l='list_path_concisely'
interactive_alias ll='list_path_verbosely'
interactive_alias lr='list_path_recursively'

# ....................{ LISTERS                            }....................
# string list_path(string ls_arg1, string ls_arg2, ...)
#
# List the passed paths (defaulting to the current directory) with the passed
# "ls" options.
list_path() {
    run_with_options 'run_paged command ls' 'ZESHY_LS_OPTIONS' "${@}"
}

# void list_path_concisely(string ls_arg1, string ls_arg2, ...)
#
# List the passed paths (defaulting to the current directory) with concise
# output and the passed "ls" options.
list_path_concisely() {
    list zeshy_ls_options; zeshy_ls_options=(
        "${ZESHY_LS_OPTIONS[@]}"
        "${ZESHY_LS_OPTIONS_IF_CONCISE[@]}"
    )
    run_with_options 'run_paged command ls' 'zeshy_ls_options' "${@}"
#   run_with_options 'run_paged command ls' 'zeshy_ls_options' ${(q)@}
}

# void list_path_verbosely(string ls_arg1, string ls_arg2, ...)
#
# List the passed paths (defaulting to the current directory) with verbose
# output and the passed "ls" options.
list_path_verbosely() {
    list zeshy_ls_options; zeshy_ls_options=(
        "${ZESHY_LS_OPTIONS[@]}"
        "${ZESHY_LS_OPTIONS_IF_VERBOSE[@]}"
    )
    run_with_options 'run_paged command ls' 'zeshy_ls_options' "${@}"
}

# void list_path_recursively(string ls_arg1, string ls_arg2, ...)
#
# List the passed paths (defaulting to the current directory) recursively with
# verbose output and the passed "ls" options.
list_path_recursively() {
    list zeshy_ls_options; zeshy_ls_options=(
        "${ZESHY_LS_OPTIONS[@]}"
        "${ZESHY_LS_OPTIONS_IF_RECURSIVE[@]}"
    )
    run_with_options 'run_paged command ls' 'zeshy_ls_options' "${@}"
}

# --------------------( WASTELANDS                         )--------------------
#is_zeshy_wrapping_core_commands and
#interactive_alias dus='list_path_disk_usage_sorted'
#   print_path_verbosely --recursive "${@}"
#   run_with_options 'run_paged command ls' 'options' "${@}"
#FIXME: This and friends below really need to be reimplemented to use "--".
#And drop all of the funcstack nonsense. Slight changes, but... *shrug*
    # "ls" command to be run.
#   list ls; ls=( run_paged command ls "${ZESHY_LS_OPTIONS[@]}" )
#       "${ls[@]}" "${ZESHY_LS_OPTIONS_IF_INTERACTIVE[@]}" "${@}"

    #FIXME: The conditional is pretty much broken. We really need to fix
    #Zeshy Digest so as to accept function aliases ala "print_path ls()".
    #Note that "content/grep" contains a similarly broken conditional.

    # If the topmost function on the function stack is "ls"-specific,
    # the current user called this function directly from the command-line.
#   if (( ${#funcstack} == 1 )) or is "${funcstack[-2]}" == print_path* si
#   then "${ls[@]}" "${ZESHY_LS_OPTIONS_IF_INTERACTIVE[@]}" "${@}"
#   else "${ls[@]}" "${ZESHY_LS_OPTIONS[@]}" "${@}"
#   fi
#

    # Call is_interactive() rather than is_interactive_directly(). The embedded
    # conditional below implicitly implements the latter, already.
    # If running non-interactively, pass *NO* Zeshy-specific options to "grep".
    # Doing so breaks non-interactive shell scripts and functions expecting
    # default "grep" behavior (e.g., basic patterns).
#   else command ls "${@}"
#   fi

#   for ((i = 1; i <= ${#funcstack}; i++)) { print "${i}: ${funcstack[${i}]}" }
#       utter "running \"${ls_command[@]} ${ZESHY_LS_OPTIONS_IF_INTERACTIVE[@]} ${@}\"..."
#   if is_interactive_directly
#   then "${ls_command[@]}" "${ZESHY_LS_OPTIONS_IF_INTERACTIVE[@]}"     "${@}"
#   else "${ls_command[@]}" "${ZESHY_LS_OPTIONS_IF_NON_INTERACTIVE[@]}" "${@}"
#   fi

#       utter "running \"${ls_command[@]} ${ZESHY_LS_OPTIONS_IF_INTERACTIVE[@]} ${@}\"..."
#       utter "options: ${ZESHY_LS_OPTIONS_IF_INTERACTIVE[@]}"#interactive_alias l='list_path'
#interactive_alias ls='list_path'
#interactive_alias ls='list_path_recursively'
#'ls --all --color=always --group-directories-first --human-readable --indicator-style=classify --quoting-style=shell --sort=version --time-style=long-iso'
#lr()  { ls --recursive               $* | less --no-init }
#ll()  { ls --format=long             $* | less --no-init }
#llr() { ls --format=long --recursive $* | less --no-init }
