#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

declare_parcel_as_script_with_stdin <<'/---'
Handle `rsync`, a CLI utility for synchronizing local with remote paths.
/---

# ....................{ PRINTERS                           }....................
declare_function_with_stdin <<'/---'
string get_rsync_modules(string hostname)

Get a newline-delimited list of all modules exposed by the remote `rsync` daemon
at the passed hostname: e.g.,

.get_rsync_modules()
==========================================
[source]
------------------------------------------
>>> get_rsync_modules "o.isis.com"
und
osiris
------------------------------------------
==========================================
/---
function get_rsync_modules() {
    die_unless_arg 'Expected one hostname.'
    command rsync --no-motd -- "${1}"::
}

# ....................{ SYNCHRONIZERS                      }....................
#FIXME: Split into interactive and non-interactive versions, the latter of
#course named rsync_with_options().
declare_function_with_stdin <<'/---'
string rsync_uri_with_options(
    string rsync_option1?, ...,
    string source_uri1, ...,
    string target_uri)

Synchronize the passed source URIs to the passed target URI with `rsync`,
passing the ZESHY_OPTIONS_RSYNC* family of default options supplemented by the
passed custom options. If running under an interactive shell, interactively
list and require the current user confirm such changes prior to permanently
doing so.

== Arguments ==

Source and target URIs may be any of the following, `[` and `]` delimiters
signifying optional parameters:

* Local paths (e.g., `/zauber/flote/`).
* SSH-style remote paths shuttled under a remote shell transport, specified as
  `[${username}@]${hostname}:${path}` (e.g., `holle@papa:/gena/`).
* rsync-style remote paths shuttled under the TCP-driven rsync daemon protocol,
  specified as either `[${username}@]${hostname}::${module}` or
  `rsync://[${username}@]${hostname}[:${port}]/${module}` (e.g.,
  `rache@papa::geno`, `rsync://herzen@papa:446/geno`). rsync modules are
  effectively pathnames mapped by the remote rsync daemon to absolute paths on
  that remote host.

If passing:

* Exactly one source URI directory, such directory should typically be
  suffixed with a trailing `/`. Omitting `/` instructs rsync to create a
  directory under the target URI directory having the same basename as such
  directory, a rarely useful instruction.
* Two or more source URI directories, such directories should typically not be
  suffixed with a trailing `/`. (See above.)

Target URIs should typically be absolute paths.

== Caveats ==

`rsync` behaves (un)intentionally destructively under certain options (e.g.,
`--delete`). As a precaution against catastrophic large-scale changes, consider
calling this function interactively when devising new synchronizations.
/---
function rsync_uri_with_options() {
    # Validate sanity.
    die_unless_args_2_or_more\
        'Expected optional rsync options, one or more source URIs, and one target URI.'
    :string last_source_uri="${@[-2]}" target_uri="${@[-1]}"
    :list rsync_command

    #FIXME: Shift to a run_code_with_options_configured()-based implementation.

    # Command line to be run.
    rsync_command=(
        :run_command_with_priority_lowest
        command rsync "${ZESHY_OPTIONS_RSYNC[@]}"
    )

    #FIXME: Clearly, we want a new function is_path_relative(). This is awkward.

    # If either the last source URI or target URI are *NOT* absolute paths, this
    # synchronization is (probably) synchronizing either to or from some remote
    # host. Append appropriate user-configured options (e.g., "--compress").
    is_path_absolute "${last_source_uri}" or
        rsync_command+=( "${ZESHY_OPTIONS_RSYNC_IF_SOURCE_REMOTE[@]}" )
    is_path_absolute "${target_uri}" or
        rsync_command+=( "${ZESHY_OPTIONS_RSYNC_IF_TARGET_REMOTE[@]}" )

    # If the current shell is interactive, interactively list and require the
    # current user confirm all filesystem changes to be performed prior to
    # permanently doing so.
    #
    # Run "rsync" deprioritized to avoid resource starvation of other processes.
    if { is_shell_interactive } {
        rsync_command+=( "${ZESHY_OPTIONS_RSYNC_IF_INTERACTIVE[@]}" )

        # List all filesystem changes to be performed prior to doing so. Since
        # users often prematurely terminate such listing with <Ctrl-C>, ignore
        # nonzero exit status.
#       print_message "running \"${rsync[@]} ${@}\"..."; sleep 2s
        print_message_item "Simulating synchronization to \"${target_uri}\"."
        "${rsync_command[@]}" --dry-run "${(q)@}" or ignore_failure

        # If the current user still wants to do so, do.
        is_query_line_yes\
            "Synchronize to \"${target_uri}\"?" or report_failure
        print_message_item "Synchronizing to \"${target_uri}\"."
        "${rsync_command[@]}" "${(q)@}"
    # Else, synchronize without interactive confirmation. Since this is
    # inherently unsafe, output a terse warning.
    } else {
        :print_warning_item\
            "Synchronizing to \"${target_uri}\" without safe simulation."
        "${rsync_command[@]}"\
            "${ZESHY_OPTIONS_RSYNC_IF_NONINTERACTIVE[@]}"\
            "${(q)@}"
    }
}

# --------------------( WASTELANDS                         )--------------------
#If implicit Consider rem
#
#The defaults, here, are probably fine.  local changes to be
#auto-overwritten by remote changes (...you probably do, but who are we to
#carp and complain), remove the "--delete" and "--delete-after" options.
#
#To improve granularity, replace "--archive" with the set of corresponding
#options (i.e., the long forms of "-rlptgoD").

    # Last source URI and target URI, for display purposes.
#   string last_source_uri="\"${@[-2]}\"" target_uri="\"${@[-1]}\""

    # If a possible prior source URI was passed, adjust the last source URI.
#   is_args_3_or_more and last_source_uri="${last_source_uri}, etc."

#       'expected one source URI, one target URI, and optional "rsync" options'

#   string source_uri="$(suffix_string "${1}" '/')" target_uri="${1}"
#   shift_args_2

    # Source and target URIs, suffixing the former with a backslash if not
    # already to satisfy "rsync" requirements. See <USAGE> for "man rsync".
#   string source_uri="$(suffix_string "${1}" '/')" target_uri="${1}"

#   , string option1, string option2, ...
    # List of "rsync" options constructed from default and passed options.
#   list rsync; rsync=( 'rsync' "${ZESHY_OPTIONS_RSYNC[@]}" "${@}" )

    #FUXME: Generalize this for use elsewhere. Specifically, use the
    #deprioritize() function of "always/process".
    # If "nice" and/or "ionice" are installed, run "rsync" under whichever are
    # available to prevent CPU and hard-drive starvation.
#   is_pathable nice   and rsync=(   nice -n19    "${rsync[@]}" )
#   is_pathable ionice and rsync=( ionice -c2 -n7 "${rsync[@]}" )
