#!/usr/bin/env zsh

declare_parcel_as_script_with_stdin <<'-/-'
Configure `zeshy`-specific SSHfuse functionality.
-/-

# ....................{ SSHFS                              }....................
#FIXME: This doesn't really belong here, but in a "ssh" config file. Actually,
#forget this. We just want a new function get_ssh_config_file() returning the
#first such file.

declare_global_with_stdin <<'/---'
list ZESHY_SSH_CONFIG_FILES

List of absolute paths to `ssh_config` files. Note that order is important:
later file content overrides that of earlier.
/---
ZESHY_SSH_CONFIG_FILES=(
    "${HOME}/.ssh/ssh_config"
    '/etc/ssh/ssh_config'
)

declare_global_with_stdin <<'/---'
map ZESHY_SSH_HOST_TO_LOCAL_PATH

Map from SSH hostname to the local pathname SSHfuse mounts such hostname to. SSH
hostnames correspond to `Host` entries in `/etc/ssh/ssh_config`. Note the
_sshfs_main() function defines acceptable defaults for all other mappings.
/---
ZESHY_SSH_HOST_TO_LOCAL_PATH=()

declare_global_with_stdin <<'/---'
map ZESHY_SSH_HOST_TO_REMOTE_PATH

Map from SSH hostname to the remote pathname SSHfuse mounts such hostname from.
See ${ZESHY_SSH_HOST_TO_LOCAL_PATH} for further details.
/---
ZESHY_SSH_HOST_TO_REMOTE_PATH=()
