#!/usr/bin/env zsh
# ====================[ partition                          ]====================
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy Partition.

# ....................{ PRINTERS                           }....................
# char *print_partitions(char *device_filename1, char *device_filename2, ...)
#
# Print the partition table for each passed device or all available disk devices
# listed by "/proc/partitions" if no such devices are passed.
print_partitions() {
    /sbin/fdisk -l "${@}"
}

# ....................{ WRITERS                            }....................
# void clone_partition_table(char *device_file1, char *device_file2)
#
# Clone the partition table from the former to latter passed device.
clone_partition_table() {
    # Localize and validate passed arguments.
    die_unless_installed sfdisk\
        '"sfdisk" required for partition table cloning but not installed'
    die_unless_two_args\
        'expected exactly one source and one target device file'
    string device_file_src="${1}" device_file_trg="${2}"
    die_unless_disk_device "${device_file_src}"
    die_unless_disk_device "${device_file_trg}"

    # Confirm.
    if ask_bool_hard "really destructively clone the partition table from "\
        "\"${device_file_src}\" onto ${device_file_trg}?"; then
        print
        sfdisk -d "${device_file_src}" | sfdisk "${device_file_trg}"
    fi
}

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyright 2007-2012 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
