#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2015 by Cecil Curry.
# See "LICENSE" for additional details.

:parcel <<'/---'
Handle core `zeshy` functionality.
/---

# ....................{ LIFECYCLERS                        }....................
:func.doc <<'/---'
void restart_zeshy()

Reload `zeshy`. If the current user's `zeshy` configuration or ${PATH} has
changed sufficiently from the current shell environment, this implicitly
recompiles the current digest file.
/---
function restart_zeshy() {
    # Validate sanity.
    die_if_args

    # Undefine a global previously defined by the main zeshy script as a
    # safeguard against accidental zeshy reloads. Since this reload is
    # intentional, remove such safeguard.
    :Var.undefine ZY_PID_LAST_LOADED_BY

    # Source the main zeshy script, thus reloading Zeshy.
    source_zeshy_script main
}

:func.doc <<'/---'
void recompile_zeshy()

Recompile and reload the current digest file, thus reloading `zeshy` itself.
/---
function recompile_zeshy() {
    # Validate sanity.
    die_if_args

    # If :compile_zeshy() is defined, call such function directly.
    if { :func.is :compile_zeshy } {
        :compile_zeshy
    # Else, Zeshy's optional component "compile" has yet to be sourced. Do so,
    # thus implicitly calling :compile_zeshy().
    } else {
        source_zeshy_script compile
    }
}

# ....................{ SOURCERS                           }....................
:func.doc <<'/---'
void source_zeshy_script(string filename1, ...)

Source the passed `zeshy` scripts in the passed order, passing each such script
no arguments.
/---
function source_zeshy_script() {
    # Validate sanity.
    die_unless_args 'Expected one or more filenames.'

    # Source such scripts.
    :str filename
    for     filename ("${@}") {
        # If such filename is prefixed with no dirname and hence is only a
        # basename,  prefix such basename with Zeshy's top-level directory.
        :str.contains "${filename}" '/' or
            filename="${ZY_HOME}/${filename}"
        source -- "${filename}"
    }
}

# --------------------( WASTELANDS                         )--------------------
# ....................{ STARTUP                            }....................
#run_hook_on_zeshy_startup startup_zeshy_version
#
#:func.doc <<'/---'
#void startup_zeshy_version()
#
#Ensure the cached Zeshy version corresponds to the current Zeshy version. If
#not, interactively usher the current user into the upgrade process.
#/---
#function startup_zeshy_version() {
#    # Validate sanity. If ignoring Zeshy's user directory, return silently.
#    die_if_args
#    is_string_nonempty "${ZY_DOT_DIR}" or :success.report
#
#    #FUXME: Obviously, should be rewritten on upgrades. I believe we intend on
#    #testing for that somewhere, yes? Wherever we end up doing that, this
#    #function should obviously be integrated into such process.
#
#    # Cache the currently installed version of Zeshy if not already cached.
#    :is_file "${ZY_USER_VERSION_FILE}" or
#        get_zeshy_version > "${ZY_USER_VERSION_FILE}"
#
#    #FUXME: Either shift somewhere more appropriate or rename this function to
#    #something more appropriate. It's pretty much just a grab-bag of
#    #miscellaneous startup code, at the moment.
#
#    # Make all other requisite paths for the current user.
#    make_dir_if_not_found "${ZY_USER_PID_DIR}"
#}
#
# ....................{ THEMES                             }....................
#declare_global_with_stdin <<'/---'
#string ZY_THEME
#
#Zeshy theme. By default, Zeshy comes bundled with:
#
#* "vanilla", the default Zeshy theme. A commendable choice, stalwart hero.
#
#Consider running print_zeshy_themes() for a human-readable list of currently
#available themes.
#/---
#ZY_THEME=vanilla

#* or  calling the external command returning such non-zero exit
#status. The definition of "documentation" depends on context.
#
#Function documentation includes all "#"-prefixed lines exactly preceding such
#function definition, themselves prefixed by either a blank line or start of
#the file (optionally followed by an ignored "# ....................{"-
#prefixed banner).
#
#Script documentation includes all "#"-prefixed lines at the top of such
#script implementation, excluding shebang lines (e.g., "#!/usr/bin/env zsh").

# ....................{ GETTERS ~ paths                    }....................
#FUXME: Rename to get_user_zeshy_dir(), in keeping with nomenclature elsewhere.
#FUXME: You know, there's really no deterministic means of reliably determining
#such path. Do we geniuinely require this function?

#:func.doc <<'/---'
#string get_user_zeshy_dot_dir(string username = "$(get_user)")
#
#Get the absolute path of Zeshy's dot directory for the passed user (defaulting
#to the current user): e.g.,
#
#.get_user_zeshy_dot_dir()
#==========================================
#[source]
#------------------------------------------
#>>> get_user_zeshy_dot_dir lydia
#/home/lydia/.zeshy
#------------------------------------------
#==========================================
#/---
#function get_user_zeshy_dot_dir() {
#    die_unless_args_0_to_1 'expected optional username'
#    :str.return "$(get_user_home "${1}")/${ZY_DOT_DIR_BASENAME}"
#}
#
# ....................{ SETUP                              }....................
#function setup_zeshy() {
#    if :shell.is_interactive
#    then setup_if_interactive
#    else noop
#    fi
#}

# ....................{ SETUP ~ interactive                }....................
# Conditionally setup interactive-only commands, if installed.
#function setup_if_interactive_installed() {
#    :pathable.is keychain and setup_keychain
#}

# If this shell is attached to a terminal device, set terminal-specific options.
#function setup_if_interactive() {
#   setup_mimetypes
#   setup_terminal
#   setup_theme_key_bindings
#   setup_theme_styles
#   setup_theme_prompt
#   setup_if_interactive_globals
#   setup_if_interactive_installed
#}

# Do so *AFTER*
    # sourcing the configuration files setting such paths.
#-- perhaps a new component of
    #"always/00-startup". There's really no profit in doing so here, is there?
#   setup_if_installed
# Conditionally setup non-interactive commands, if installed.
#function setup_if_installed() {
#    run_code_if_pathable setup_x
#}

#FUXME: Eventually, we'll have to add a setup hooks list and functions for
#adding setup hooks to such list. This is a hard requisite, as users may like to
#add new components not explicitly conceived of here. Assuming such a framework,
#no explicit tests are required here. It's also much easier to maintain, since
#it couples setup logic to the components implementing such functions.

# ....................{ SETUP ~ non-interactive            }....................
#function setup_if_non_interactive() {
#   print "process command name: $(get_process_command_name)"
#}

#   setup_interactive_gui_substitutions
#   else source "${ZY_HOME}/compile"
    #FUXME: Shift setting of "PAGER" to "terminal/output/pager".
#       PAGER="${PAGER:-"$(get_pathable_path_first less more)"}"
    # Set the default script name prior to all other logic, as any logic
    # raising an error requires this name for logging that error. Only do this
    # if the current process is not an interactive zsh shell as, in that case,
    # the output_call_stack_root_in_style() function dynamically inspects the script name from
    # the function call stack.
    # Strip the filetype from this script's basename, if present.
#   string_global_export ZY_SCRIPT_FILENAME="${$(get_process_command_name)%%.*}"

    # Default the script name to "zeshy", if "zsh".
#   is "${ZY_SCRIPT_FILENAME}" == zsh si and ZY_SCRIPT_FILENAME=zeshy
