#!/usr/bin/env zsh
# ====================[ boolean                            ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Define integer global contants.

# ....................{ BOOLEANS                           }....................
declare_global_with_stdin <<'________________<heredoc?>________________'
boolean ZESHY_BOOLEAN_FALSE

Arbitrary string signifying a boolean false value. Since `zsh` supports no
boolean type, we emulate such type with string constants.
________________<heredoc?>________________
ZESHY_BOOLEAN_FALSE=

declare_global_with_stdin <<'________________<heredoc?>________________'
boolean ZESHY_BOOLEAN_TRUE

Arbitrary string signifying a boolean true value. Since `zsh` supports no
boolean type, we emulate such type with string constants.
________________<heredoc?>________________
ZESHY_BOOLEAN_TRUE='true'

# --------------------( WASTELANDS                         )--------------------
