#!/usr/bin/env zsh
# ====================[ 7z                                 ]====================
#                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy 7-zip, implementing "7z"-specific functionality.

# ....................{ ENCRYPTION                         }....................
# void 7z_encrypt_dir(char *dirname)
#
# Encrypt (but do not compress) the passed directory as a 7-zip archive.
7z_encrypt_dir() {
    die_unless_one_argument 'expected exactly one dirname'
    curse 'please consider a password of at least 17 characters, if security genuinely matters!'
    curse 'please note this command assumes media and hence performs no additional compression!'
    utter 'if you require such compression, consider 7z_encrypt_compress_dir()'

    archive_dir "${1}" 7z\
        7z 'a' '-mhe=on -mx0 -p'\
        7z 'l' ''
}

# void 7z_encrypt_compress_dir(char *dirname)
#
# Encrypt and compress the passed directory as a 7-zip archive.
7z_encrypt_compress_dir() {
    die_unless_one_argument 'expected exactly one dirname'
    curse 'please consider a password of at least 17 characters, if security genuinely matters!'
    curse 'please note this command performs additional compression and hence consumes more time!'
    utter 'if you do not require such compression, consider 7z_encrypt_dir()'

    archive_dir "${1}" 7z\
        7z 'a' '-mhe=on -p'\
        7z 'l' ''
}

#FIXME: Obsolete.
#   die_unless_at_most_two_arguments\
#       'expected one source dirname to encrypt and one optional target filename to encrypt to'
#   string dirname="${1}"
#   string 7z_filename="${2:-dirname}"

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyright 2007-2012 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
