#!/usr/bin/env zsh
# ====================[ mysql                              ]====================
#                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy MySQL. This Zeshy component handles MySQL functionality.

# ....................{ ALIASES                            }....................
# MySQL options for the interactive MySQL shell.
ZESHY_MYSQL_OPTIONS=(
    --pager=less
    --auto-rehash
    --chop-long-lines 
    --column-names
    --compress
    --ignore-case
    --line-numbers
    --named-commands
    --no-beep
    --password
    --reconnect
    --secure-auth
    --show-warnings
    --sigint-ignore
    --skip-comments
    --table
)

alias mysql="mysql ${ZESHY_MYSQL_OPTIONS[@]}"
alias mysql_as_root="mysql --user=root --host=localhost"

# ....................{ GETTERS                            }....................
# void mysql_print_about()
#
# Print MySQL-specific metadata, including:
#
# * Version.
mysql_print_about() {
    [[ "${#}" -eq 0 ]] || die 'expected no arguments'

    # Temporary file to which we write Apache output.
    local mysql_output_file=$(which_temporary_file 'mysql-about')

    # Append Apache-specific output to this file.
    try mysql -V >> "${mysql_output_file}"

    # Show it; kill it.
    less "${mysql_output_file}"
    rm "${mysql_output_file}"
}

# ....................{ SETTERS                            }....................
# void mysql_set_password(char *username, char *password)
#
# Set the passed password for the passed MySQL username. Username defaults to
# "root", if not passed. Note that new users are best created via interactive
# "CREATE USER" SQL commands entered as the root user.
mysql_set_password() {
    [[ "${#}" -ge 1 ]] || die 'expected at least a password'

    local username password
    if [[ -n "${2}" ]]; then
        username="${1}"
        password="${2}"
    else
        username="root"
        password="${1}"
    fi

    utter "setting \"${username}\" password..."
    try mysqladmin -u "${username}" password "${password}"
}

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyright 2007-2011 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
