#!/usr/bin/env zsh
# ====================[ pdftotext                          ]====================
#                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy pdftotext. This Zeshy component handles "pdftotext" functionality, a
# command-line utility for extracting plaintext from Adobe PDF files.

# ....................{ FUNCTIONS                          }....................
# void pdftotext_dir(char *dirname)
#
# Run "pdftotext" on all PDF files in the passed directory.
pdftotext_dir() {
    [[ "${#}" -le 1 ]] || die 'expected no arguments or an optional dirname'
    local dirname=${1:-${PWD}}

    utter "extracting plaintext from PDF files in \"${dirname}\"..."
    try pushd "${dirname}"

    # Do not bother dying if "pdftotext" fails, as it occasionally does on
    # poorly formatted PDF files.
    find -iname '*.pdf' -exec pdftotext {} \;

    try popd
}

# ....................{ GREP                               }....................
# void grep_pdf(char *pattern, char *filename)
#
# Grep the passed PDF file for the passed pattern.
grep_pdf() {
    [[ "${#}" -eq 2 ]] ||
        die "expected exactly one regular expression and one filename"

    local pattern="${1}"
    local filename="${2}"

    [[ "${filename}" == *.pdf ]] || die "\"${filename}\" not a PDF file"
    pdftotext "${filename}" |
        grep ${=ZESHY_GREP_OPTIONS} "${pattern}" |
        "${PAGER}"
}

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyright 2007-2011 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
