#!/usr/bin/env zsh
# ====================[ pathable                           ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Handle pathable-specific functionality called from a top-level context.

# ....................{ TESTERS                            }....................
declare_function_with_stdin <<'________________<heredoc?>________________'
[status: boolean] is_pathable_gnu(string command_name)

Return success if the passed command is in the current ${PATH} _and_ the GNU
implementation of such command. GNU implementations often implement helpful, if
non-standard, options in both machine-readable short form and human-readable
long form either not available in alternate implementations (e.g., `grep` option
`--perl-regexp`) or available in short form (e.g., common option `--version`).
________________<heredoc?>________________
function is_pathable_gnu() {
    # Validate sanity.
    die_unless_arg 'expected one command name'
    string command_name="${1}"

    # Return success if the following conditions are all true:
    #
    # * Such command is in the current ${PATH}. See get_pathable_path_if_found()
    #   for further details.
    # * Such command successfully returns its version given a GNU-style option.
    # * Such version contains "GNU".
    is "${command_name:t:c}" == '/'* si and {
        string output
        output="$(command "${command_name}" --version 2>&/dev/null)" and
            is "${output}" == *'GNU'* si
    }
}

# --------------------( WASTELANDS                         )--------------------
#FUXME: Shift somewhere more appropriate. Perhaps we want a new component
#"runnable/pathable/gnu", for example. Ah; right. Such functions must be
#available early. Hence, shift to component "00-startup/15-pathable/gnu".
#FUXME: Replace with a more general function -- say, is_pathable_gnu().
#FUXME: Replace the call to is_pathable() with its underlying implementation.
