#!/usr/bin/env zsh

declare_parcel_as_script_with_stdin <<'/---'
Configure `zeshy`-specific X11 functionality.
/---

# ....................{ ALIASES                            }....................
# See "00-core/alias" for further details.

ZESHY_ALIAS_CLI_ABBREVIATIONS+=(
    {l}s{xf}ont 'print_x_fonts'
)
