#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

:parcel <<'/---'
Handle *terminal color printers* (i.e., functions printing terminal colors and
related globals).
/---

# ....................{ PRINTERS                           }....................
#FIXME: Aesthetically improve output. Ultimately, such output should resemble in
#at least inspiration the novel color figures output by the 20Kb Python script
#"xterm_colour_chart.py". Barring that, however, it would be nice to at least
#convert this to call print_table_cells() with suffixing option "column_count 2",
#when such function is up and running.
#FIXME: The current implementation of this function is specific to 256 colors.
#Clearly, that's wrong: generalize this to however many colors the current
#terminal supports.

declare_function_with_stdin <<'/---'
string :print_x11_colors()

Print a human-readable synopsis of all canonical X11 colors (e.g., `honeydew`),
as displayed under the current terminal.
/---
function :print_x11_colors() {
    # Validate sanity.
    die_if_args

    # Define ${ZESHY_X11_COLOR_NAME_TO_COLOR_ANSI_256}.
    define_global_x11_color_name_to_color_ansi_256

    # Display colors defined by such map.
    {
        print_message_heading 'X11 to Terminal Color Map'

        :string color_name color_value
        for     color_name color_value (
            "${(kv@)ZESHY_X11_COLOR_NAME_TO_COLOR_ANSI_256}") {
            :string.output "${color_name} ${ZESHY_X11_COLOR_NAME_TO_RGB_HEXADECIMAL[background=${color_name}]}"
        } | tabulate_stdin
    } | page_stdin
}

# --------------------( WASTELANDS                         )--------------------
