#!/usr/bin/env zsh

declare_parcel_as_script_with_stdin <<'/---'
Configure `cd`, a builtin command changing the current directory.
/---

# ....................{ CD                                 }....................
declare_global_with_stdin list ZESHY_OPTIONS_CD <<'/---'
`cd` options for `zeshy`-specific directory setters (e.g., change_dir()).
/---
ZESHY_OPTIONS_CD=()

declare_global_with_stdin list ZESHY_OPTIONS_CD_IF_INTERACTIVE <<'/---'
`cd` options when run interactively.
/---
ZESHY_OPTIONS_CD_IF_INTERACTIVE=()

declare_global_with_stdin list ZESHY_OPTIONS_CD_IF_NONINTERACTIVE <<'/---'
`cd` options when run non-interactively.
/---
# If non-interactive, change directories idempotently (i.e., without hidden side
# effects) by not implicitly calling builtin chpwd() or any functions registered
# with run_hook_after_dir_set_interactively(). See change_dir() for further details.
ZESHY_OPTIONS_CD_IF_NONINTERACTIVE=(
    -q
)

#FIXME: Do we actually call change_dir_idempotently() anywhere? Honestly, given the
#existence of store_dir() and restore_dir(), this strikes me as overkill.
declare_global_with_stdin list ZESHY_OPTIONS_CD_IF_IDEMPOTENT <<'/---'
`cd` options when run idempotently (i.e., without inducing side effects by
calling hook functions). See change_dir_idempotently() for further details.
/---
ZESHY_OPTIONS_CD_IF_IDEMPOTENT=()
