#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

declare_parcel_as_script_with_stdin <<'/---'
Handle *argument lists* (i.e., lists of all arguments passed to functions and
scripts).
/---

# ....................{ [AP|PRE]PENDERS                    }....................
:declare_alias_simple 'void {prepend_arg, unshift_arg}(string arg)'\
    '{ set_args "$(get_stdin)" "${@}" } <<<' <<'/---'
Prepend the passed argument to the beginning of the current argument list. Due
to `zsh` constraints, this alias accepts only a single such argument.
/---

:declare_alias_simple 'void {append_arg, push_arg}(string arg1, ...)'\
    'set_args "${@}"' <<'/---'
Append the passed arguments to the end of the current argument list.
/---

# ....................{ SHIFTERS                           }....................
:declare_alias_simple 'void shift_args(integer arg_count = 1)'\
    'shift --' <<'/---'
Remove the passed number of arguments (defaulting to 1) from the beginning of
the current argument list.
/---

:declare_alias_simple 'void shift_arg(void)' 'argv[1]=()' <<'/---'
Remove the first argument from the current argument list.
/---

:declare_alias_simple 'void shift_args_2(void)' 'argv[1,2]=()' <<'/---'
Remove the first two arguments from the current argument list.
/---

:declare_alias_simple 'void shift_args_3(void)' 'argv[1,3]=()' <<'/---'
Remove the first three arguments from the current argument list.
/---

# ....................{ POPPERS                            }....................
:declare_alias_simple 'void pop_args(integer argument_count)'\
   '{
        # Validate sanity.
        string count__pa; count__pa="$(get_stdin)"
        die_unless_arg_index "${count__pa}"

        # Pop such arguments.
        argv[-${count__pa},-1]=()
    } <<<' <<'/---'
Remove the passed number of arguments from the end of the current argument list.
/---

:declare_alias_simple 'void pop_arg(void)' 'argv[-1]=()' <<'/---'
Remove the last argument from the current argument list.
/---

:declare_alias_simple 'void pop_args_2(void)' 'argv[-2,-1]=()' <<'/---'
Remove the last two arguments from the current argument list.
/---

:declare_alias_simple 'void pop_args_3(void)' 'argv[-3,-1]=()' <<'/---'
Remove the last three arguments from the current argument list.
/---

# --------------------( WASTELANDS                         )--------------------
#FUXME: Also define a new generalized remove_args() function 
