#!/usr/bin/env zsh
# ====================[ media                              ]====================
#                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy Media. This Zeshy component implements media-specific functionality.

# ....................{ PATHS                              }....................
# Directory to which Zeshy mounts media.
export ZESHY_MOUNT_HOME='/media'

# Directory to which Zeshy mounts ISOs.
export ZESHY_MOUNT_ISO_PATH="${ZESHY_MOUNT_HOME}/iso"

#FIXME: Generalize to non-Linux *nix platforms.
# File to which Zeshy inspects existing mount points.
export ZESHY_MOUNT_POINTS_FILE="/proc/mounts"

# ....................{ ALIASES                            }....................
# Images.
dia()    { command dia $* & } 
geeqie() { command geeqie $* & } 
gimp()   { command gimp $* & } 

# Images. (Inkscape.)
inkscape() { command inkscape $* & } 
inkscape_export_eps() {
  inkscape $* --export-eps="${1}.eps"
}
inkscape_export_pdf() {
  inkscape --export-area-drawing $* --export-pdf="${1}.pdf"
}

# Videos.
vlc() { command vlc $* & }

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyleft 2007-2010 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
