#!/bin/zsh
# ====================[ zshrc.ssh                          ]====================
#                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Zsh style definitions. This principally means completion configuration, at the
# moment.

# ....................{ COMPLETIONS                        }....................
# To install and configure completions by menu, rather than hand, run:
#    compinstall

# The following lines were added by compinstall

zstyle ':completion:*' completer _oldlist _complete _match _approximate _prefix
zstyle ':completion:*' expand suffix
zstyle ':completion:*' format '[completing %d}'
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' match-original both
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'r:|[._-]=** r:|=**'
zstyle ':completion:*' max-errors 1
zstyle ':completion:*' menu select=long-list select=0
zstyle ':completion:*' prompt '[corrected %e}'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' verbose true

autoload -Uz compinit
#compinit
# End of lines added by compinstall

# Use an active menu, rather than passive list, for TAB completions.
# zstyle ':completion:*' menu select=1

# Colorize TAB completions.
# zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'

# Cache TAB completions, so as to improve TAB completion responsivity.
zstyle ':completion::complete:*' use-cache on
zstyle ':completion::complete:*' cache-path "${ZSH_COMPLETION_CACHE_PATH}"

# Ignore completion functions for commands we don't have.
zstyle ':completion:*:functions' ignored-patterns '_*'

# When TAB completing pathnames, strip the trailing slash. (Nice for "ln".)
zstyle ':completion:*' squeeze-slashes true

# When TAB completing for "cd", ignore the current and parent paths.
# zstyle ':completion:*:cd:*' ignore-parents parent pwd

# Initialize completions after defining all completions above. It is especially
# important this be done after defining the cache path, otherwise logging in as
# root ejaculates the following interactive error:
# 
#     zsh compinit: insecure directories, run compaudit for list.
#     Ignore insecure directories and continue [y] or abort compinit [n]?
compinit -i -d "${ZSH_COMPINIT_DUMP_FILE}"

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyleft 2007-2010 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
