#!/usr/bin/env zsh
# ====================[ terminal                           ]====================
#                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy Terminal. This Zeshy component implements terminal-handling
# functionality, typically related to the "visual" command-line interface.
#
# --------------------( FIXME                              )--------------------
# * Shift Zeshy Color functionality into this component. No sense in cluttering
#   up the interface with two orthogonal terminal interface components!

# ....................{ SIZE                               }....................
# int get_terminal_width(void)
#
# Get the width in characters of the current terminal.
get_terminal_width() {
    die_unless_no_arguments
    echo "${COLUMNS}"
}

# ....................{ WIDGETS                            }....................
# void utter_banner(void)
#
# Print a one-line "banner," visually demarcating subsequent from prior lines. 
utter_banner() {
    die_unless_no_arguments
    echo "${(l.$(get_terminal_width)..=.)}"
}

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyright 2007-2012 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
