#!/usr/bin/env zsh
# ====================[ boolean                            ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2012 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Handle boolean variables.

# ....................{ EXCEPTIONS                         }....................
# void die_unless_boolean(
#   string variable_name,
#   string error_message = "\"${variable_name}\" not a boolean")
#
# Throw an exception unless the passed variable is a boolean.
function die_unless_boolean() {
    die_unless_args_1_to_2\
        'expected one variable name and optional error message'
    string variable_name="${1}"
    is_boolean "${variable_name}" or
        die "${2:-\"${variable_name}\" not a boolean}"
}

# ....................{ TESTERS                            }....................
# boolean is_boolean(string variable_name)
#
# Return true if the passed variable is an boolean.
function is_boolean() {
    # Since booleans are currently indistinguishable from strings under Zsh,
    # defer to is_string().
    die_unless_arg 'expected one variable name'
    is_string "${@}"
}

# boolean is_boolean_false(string variable_name)
#
# Return true if the passed variable is a false boolean (i.e., empty string).
function is_boolean_false() {
    die_unless_arg 'expected one string'
    string variable_name="${1}"
    is_boolean "${variable_name}" and is -z "${(P)variable_name}" si
}

# boolean is_boolean_true(string variable_name)
#
# Return true if the passed variable is a true boolean (i.e., non-empty string).
function is_boolean_true() {
    die_unless_arg 'expected one string'
    string variable_name="${1}"
    is_boolean "${variable_name}" and is -n "${(P)variable_name}" si
}

# --------------------( WASTELANDS                         )--------------------
