#!/usr/bin/env zsh

:parcel <<'/---'
Configure `zeshy`-specific `rsync` functionality.
/---

# ....................{ OPTIONS                            }....................
:list.global ZY_OPTIONS_RSYNC <<'/---'
`rsync` options for `zeshy`-specific synchronizers (e.g.,
rsync_uri_with_options()).
/---
# Default options silently overwrite target with source changes, including
# deletion of all files found on the target but not source. While this is
# normally desirable, consider removing options "--delete" and "--delete-after"
# if your needs differ.
ZY_OPTIONS_RSYNC=(
    # Ignore temporary files.
    --exclude='*.swp'

    # Delete all files found on the target but not source.
    --delete

    # Synchronize device and special files as well as normal files.
    --devices --specials

    # Synchronize symbolic links.
    --links --keep-dirlinks --safe-links

    # Avoid crossing filesystem boundaries (i.e., synchronize only files
    # residing on filesystems to which the target URIs themselves are mounted).
    --one-file-system

    # Attempt to preserve file permissions and ownership.
    --perms --group --owner
    --protect-args

    # Synchronize recursively.
    --recursive
    --sparse
    --timeout=32
    --times
)

:list.global ZY_OPTIONS_RSYNC_IF_INTERACTIVE <<'/---'
`rsync` options when run interactively.
/---
ZY_OPTIONS_RSYNC_IF_INTERACTIVE=(
    --human-readable
    --itemize-changes
    --progress
    --stats
)

:list.global ZY_OPTIONS_RSYNC_IF_NONINTERACTIVE <<'/---'
`rsync` options when run non-interactively. For safety, such options typically
enable safeguards against accidental large-scale deletions.
/---
ZY_OPTIONS_RSYNC_IF_NONINTERACTIVE=(
    --max-delete=128
    --quiet
)

:list.global ZY_OPTIONS_RSYNC_IF_SOURCE_REMOTE <<'/---'
`rsync` options when at least one source URI is remote.
/---
ZY_OPTIONS_RSYNC_IF_SOURCE_REMOTE=(
    --compress
)

:list.global ZY_OPTIONS_RSYNC_IF_TARGET_REMOTE <<'/---'
`rsync` options when at least one target URI is remote.
/---
ZY_OPTIONS_RSYNC_IF_TARGET_REMOTE=(
    --compress
)
