#!/usr/bin/env zsh

declare_parcel_as_script_with_stdin <<'-/-'
Configure `zeshy`-specific `rsync` functionality.
-/-

# ....................{ OPTIONS                            }....................
#FIXME: Rename to ${ZESHY_OPTIONS_RSYNC}.
declare_global_with_stdin <<'/---'
list ZESHY_RSYNC_OPTIONS

`zeshy`-specific `rsync` options (e.g., for rsync_safely()).
/---
# Default options silently overwrite target with source changes, including
# deletion of all files found on the target but not source. While this is
# normally desirable, consider removing options "--delete" and "--delete-after"
# if your needs differ.
ZESHY_RSYNC_OPTIONS=(
    --exclude='*.swp'
    --delete
    --devices --specials
    --links --keep-dirlinks --safe-links
    --one-file-system
    --perms --group --owner
    --protect-args
    --recursive
    --sparse
    --timeout=32
    --times
)

declare_global_with_stdin <<'/---'
list ZESHY_RSYNC_OPTIONS_IF_INTERACTIVE

`zeshy`-specific `rsync` options when run from the interactive command line.
/---
ZESHY_RSYNC_OPTIONS_IF_INTERACTIVE=(
    --human-readable
    --itemize-changes
    --progress
    --stats
)

declare_global_with_stdin <<'/---'
list ZESHY_RSYNC_OPTIONS_IF_NONINTERACTIVE

`zeshy`-specific `rsync` options when run from non-interactive scripts. For
safety, such options typically enable safeguards against large-scale deletions.
/---
ZESHY_RSYNC_OPTIONS_IF_NONINTERACTIVE=(
    --max-delete=128
    --quiet
)

#FIXME: Rename to ${ZESHY_OPTIONS_RSYNC_IF_SOURCE_REMOTE}.
declare_global_with_stdin <<'/---'
list ZESHY_RSYNC_OPTIONS_IF_REMOTE_SOURCE

`zeshy`-specific `rsync` options when at least one source path resides on a
remote host.
/---
ZESHY_RSYNC_OPTIONS_IF_REMOTE_SOURCE=(
    --compress
)

#FIXME: Rename to ${ZESHY_OPTIONS_RSYNC_IF_TARGET_REMOTE}.
declare_global_with_stdin <<'/---'
list ZESHY_RSYNC_OPTIONS_IF_REMOTE_TARGET

`zeshy`-specific `rsync` options when at least one target path resides on a
remote host.
/---
ZESHY_RSYNC_OPTIONS_IF_REMOTE_TARGET=(
    --compress
)
