#!/usr/bin/env zsh
# ====================[ net                                ]====================
#                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy Net, implementing network-handling functionality.

# ....................{ ALIASES                            }....................
interactive_alias wgetpaste='wgetpaste --verbose'

# ....................{ WRITERS ~ local                    }....................
# void unbind_ip_address(char *ip_address, char *device_name = 'eth0')
#
# Unbind the passed IP address from the passed network device, defaulting to
# "eth0" if unpassed:e.g.,
#
#     >>> unbind_ip_address 10.0.0.2 eth0
unbind_ip_address() {
    die_unless_one_or_two_arguments\
        'expected one IP address and optionally one device name'

    # Parse arguments.
    string ip_address="${1}"
    string device_name="${2:-eth0}"

    # Utter truth.
    utter "unbinding IP address ${ip_address} from ${device_name}..."
    
    #FIXME: Add support for "ifconfig", if "ip" not runnable. Also, ensure that
    #"${2}" refers to a real network device.
    is_installed ip or die "\"ip\" not installed"
    ip addr del "${ip_address}" dev "${device_name}"
}

# ....................{ WRITERS ~ remote                   }....................
# void pastebin(char *filename)
#
# Upload the contents of some file as a pastebin post. This file will be posted
# as a plain textfile, and is thus best used for logs.
pastebin() {
    die_unless_one_argument 'expected exactly one filename'
    string pastebin_file="${1}"
    die_unless_file "${pastebin_file}"
    die_unless_installed wgetpaste

    utter "pasting ${pastebin_file}..."
    cat "${pastebin_file}" | wgetpaste --raw
}

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyright 2007-2012 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
