#!/usr/bin/env zsh
# ====================[ eix                                ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2012 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Handle Gentoo ebuild caching and searching.

# ....................{ ALIASES                            }....................
#FIXME: Shift to a new "if_installed/q" component. Also, this should be calling
#a new list_files_installed_by_ebuild() function.
interactive_abbreviation {e}merge{q}uery{l}ist='run_paged qlist'

# ....................{ TESTERS                            }....................
# boolean is_eix_synchronizing_overlays(void)
#
# Return true if "eix" is configured to synchronize added overlays along with
# the Portage tree when running "eix-sync". This is true if and only if
# "/etc/eix-sync.conf" contains the single character "*".
function is_eix_synchronizing_overlays() {
    # Validate sanity.
    # Unless "/etc/eix-sync.conf" contains only "*", return false.
    die_if_args
    string eix_sync_filename eix_sync_contents
    is_file_text_equals "$(get_eix_synchronization_configuration_file)" '*'
}

# ....................{ GETTERS                            }....................
# string get_eix_synchronization_configuration_file(void)
#
# Get the absolute path of the synchronization-specific configuration file for
# "eix" (e.g., "/etc/eix-sync.conf").
function get_eix_synchronization_configuration_file() {
    die_if_args
    print_string '/etc/eix-sync.conf'
}

# ....................{ PRINTERS                           }....................
# string print_eix_settings(void)
#
# Print a human-readable list of current "eix" settings, complete with comments.
function print_eix_settings() {
    die_if_args
    run_paged eix --dump
}

# string print_eix_ebuild_match_pcrees(string regex)
#
# Print all ebuilds with names and/or descriptions matching the passed regular
# expression. This assumes a prior call to update_eix() created the "eix" cache.
function print_eix_ebuild_match_pcrees() {
    # Validate passed arguments.
    die_unless_arg 'expected one regex'
    string regex="${1}"

    # Command line to be run. If attached to a terminal, force "eix" to display
    # colors. Running under run_paged() wickedly seduces "eix" into believing
    # that it's not attached to a terminal -- when, in fact, it is (by proxy of
    # the pager paging its output).
    list eix; eix=( eix )
    is_standard_output_terminal and eix+='--force-color'

    # First search ebuild names; then, descriptions. Append "or true" to avoid
    # throwing an exception on failing to match either.
    {
        say_first_section "ebuild names matching \"${regex}\""
        "${eix[@]}"    -- "${regex}" or true
        say_next_section  "ebuild descriptions matching \"${regex}\""
        "${eix[@]}" -S -- "${regex}" or true
    } | page_string
}

# ....................{ UPDATERS                           }....................
# void update_portage_with_eix(void)
#
# Update the main Portage tree, all available overlays, and the "eix" cache with
# new or revised ebuilds.
function update_portage_with_eix() {
    # Validate sanity.
    die_if_args

    # If "eix" is *NOT* configured to synchronize added overlays and "layman" is
    # installed, synchronize
    boolean is_first_section_printed
    not is_eix_synchronizing_overlays and
        is_gentoo_overlay_command_installed and {
        is_first_section_printed=1
        interactively say_first_section 'updating added overlays'
        update_gentoo_overlays
    }

    # Update the main Portage tree and possibly all added overlays.
    if is_nonempty "${is_first_section_printed}"
    then interactively say_next_section  'updating portage'
    else interactively say_first_section 'updating portage'
    fi
    eix-sync

    # Update the "eix" cache with all ebuilds in all overlays, added or not.
    is_gentoo_overlay_command_installed and {
        interactively say_next_section  'updating all overlays'
        eix-remote update
    }
}

# --------------------( WASTELANDS                         )--------------------
    # Unless "/etc/eix-sync.conf" exists, return false.
#   eix_sync_filename="$(get_eix_synchronization_configuration_file)"
#   is_file "${eix_sync_filename}" or return_false

#   is "$(get_file_text "${eix_sync_filename}")" == '*' si
#   eix_sync_contents="$(get_file_text "${eix_sync_filename}")"
#   is "${eix_sync_contents}" == '*' si

    #FIXME: Add support for Paludis-driven overlay synchronization. This
    #suggests a new is_gentoo_overlays_supported() function returning true if
    #either "layman" or "cave" are installed.

    # If no ebuild name matches, attempt to match ebuild descriptions as a
    # desperate, doomed fallback.
