#!/usr/bin/env zsh
# ====================[ prompt                             ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2012 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Handle interactive shell prompts.
#
# --------------------( SEE ALSO                           )--------------------
# http://aperiodic.net/phil/prompt/
#   Phillip Gold's fairly phenomenal "ZSH Prompt" treatise.
#
# --------------------( TODO                               )--------------------
# * Incorporate the following other prompt scripts:
#  * Has a fantastic series of functions for setting the terminal title!
#    http://www.semicomplete.com/misc/rcfiles/zshrc

# ....................{ SPLASH                             }....................
# Display introductory "splash" text. This is a line or two of text displayed
# prior to displaying the shell prompt, on initial start-up of the shell.
#
# This text is defined and displayed according to ZSH shell prompt syntax.
# Thus, see "info zsh" for details.

# ....................{ HOOKS                              }....................
# void precmd()
#
# Modifies the current shell environment prior to printing the current prompt.
# Zsh runs this function immediately after the process for the previous command
# completes but immediately before printing another prompt for the next command.
#precmd() {
#}

# void preexec(string command_name, string command_arg_1, ...)
#
# Modifies the current shell environment prior to running the passed command.
# Zsh runs this function immediately after the current user inputs a command at
# the current prompt and then inputs <Enter>, but immediately before executing
# the command.
function preexec() {
    # Force this command's print_string to be bold white, regardless of the previous
    # color print_string by this command's prompt.
    print -Pn -- "${FG_WHITE}"
}

# ....................{ STARTUP                            }....................
append_command_to_zeshy_startup_if_shell_interactive\
    startup_zeshy_terminal_prompt

document_function '
void startup_zeshy_terminal_prompt(void)

Define prompt strings for the current interactive shell. This includes:

* ${PROMPT}, the default leftmost prompt string.
* ${PROMPT2}, the leftmost prompt string for continuation lines.
* ${PROMPT3}, the leftmost prompt string for "select" loops.
* ${PROMPT4}, the leftmost prompt string for runtime traces.
* ${RPROMPT}, the default rightmost prompt string.
* ${SPROMPT}, the leftmost prompt string for spelling mistake corrections.
'
function startup_zeshy_terminal_prompt() {
    # Validate sanity.
    die_if_args
    die_unless_shell_interactive
    string color_command color_machine color_path color_exit_status_nonzero

    # Define user-specific colors to be used in prompts below.
    if is_current_user_superuser; then
        color_command=${FG_GREY}
#       color_command=${FG_BLACK_BOLD}
        color_machine=${FG_RED}
        color_path=${FG_WHITE}
        color_exit_status_nonzero=${FG_MAGENTA}
    else
        color_command=${FG_WHITE_BOLD}
        color_machine=${FG_CYAN}
        color_path=${FG_GREEN}
        color_exit_status_nonzero=${FG_RED}
    fi

    #FIXME: This can be simplified by noting the only difference between the root
    #and non-root prompts are the colors and that, therefore, this difference may
    #be abstracted out by defining these colors in a pre-prompt Zsh function.

    # Define (and export) the ANSI shell prompt. To view this prompt as colorized
    # output, type "print -P $PS1"; and to view and edit this prompt as plaintext
    # source, type "vared PS1".
    #
    # This text is defined and displayed according to ZSH shell prompt syntax.
    # See "info zsh" for details.
    PROMPT=''
    PROMPT+="${color_command}[${color_machine}%m %B%n${color_command}}"   # user
    PROMPT+="${color_path}%~"                                             # path
    PROMPT+="%B%(1/?%(0??${color_path}/?${color_exit_status_nonzero}!)?)" # last process failed?
    PROMPT+="${color_command}"                                            # input

    # Set no rightmost prompt.
    RPROMPT=
#   export RPROMPT=
#   print "PS1: ${PS1}"
}

# --------------------( WASTELANDS                         )--------------------
#   export PS1
    #export PS1="%(!?${FG_BLACK_BOLD}[${FG_RED}%m %B%n${FG_BLACK_BOLD}}${FG_WHITE}%~%B%(1/?%(0??${FG_WHITE}/?${FG_RED}!)?)${FG_BLACK_BOLD}?${FG_WHITE_BOLD}[${FG_CYAN}%m %B%n${FG_WHITE_BOLD}}${FG_GREEN}%~%B%(1/?%(0??${FG_GREEN}/?${FG_RED}!)?)${FG_WHITE_BOLD})"

#FUXME: Obsolete.
# * "${PS1}", the core shell prompt variable, in a root-aware manner.
# * Splash message, terse introductory text welcoming the current user to Zeshy.
# * Help message, verbose synopsizing Zeshy functionality, issues, and usage
