#!/usr/bin/env zsh
# ====================[ zeshy                              ]====================
#
# --------------------( SYNOPSIS                           )--------------------
# Configure basic Zeshy settings.

# ....................{ DECLARATIONS                       }....................
boolean_global_export\
    ZESHY_RELEASE_IS_DEBUG\
    ZESHY_IS_ERROR_HANDLER_PRINTING_CALL_STACK\
    ZESHY_IS_ERROR_HANDLER_PRINTING_DOCUMENTATION\
    ZESHY_IS_ERROR_HANDLER_PRINTING_SOURCE_CODE\
    ZESHY_IS_SUBSTITUTING_INTERACTIVE_COMMANDS\
    ZESHY_IS_ABBREVIATING_INTERACTIVE_COMMANDS
integer_global_export\
    ZESHY_DIR_STACK_MAX_SIZE
string_global_export\
    ZESHY_DOT_CACHE_DIR\
    ZESHY_DOT_COMPINIT_FILE\
    ZESHY_DOT_COMPLETION_DIR\
    ZESHY_DOT_CACHE_DOCUMENTATION_DIR\
    ZESHY_DOT_CACHE_DOCUMENTATION_ALIAS_DIR\
    ZESHY_DOT_CACHE_DOCUMENTATION_FUNCTION_DIR\
    ZESHY_DOT_CACHE_DOCUMENTATION_GLOBAL_DIR\
    ZESHY_DOT_PID_DIR\
    ZESHY_INITRAMFS_HOME\
    ZESHY_THEME

# ....................{ THEMES                             }....................
# Zeshy theme. Choices include:
#
# * "vanilla", the default Zeshy theme. (A most commendable choice, kind Sir.)
ZESHY_THEME=vanilla

# ....................{ PATHS                              }....................
# Directory to which Zeshy caches transient files and directories.
ZESHY_DOT_CACHE_DIR="${ZESHY_DOT_DIR}/cache"

#FIXME: Rename to ZESHY_DOT_CACHE_COMPINIT_DIR.
# File to which compinit() caches completion initialization.
ZESHY_DOT_COMPINIT_FILE="${ZESHY_DOT_CACHE_DIR}/compinit"

#FIXME: Rename to ZESHY_DOT_CACHE_COMPLETION_DIR.
# Directory to which Zsh caches completion results.
ZESHY_DOT_COMPLETION_DIR="${ZESHY_DOT_CACHE_DIR}/completion"

#FIXME: Rename to ZESHY_DOT_CACHE_PID_DIR.
# Directory to which Zeshy caches process IDs.
ZESHY_DOT_PID_DIR="${ZESHY_DOT_CACHE_DIR}/pid"

# ....................{ PATHS ~ documentation              }....................
# Directory to which Zeshy caches documentation for Zeshy-specific aliases,
# functions, and globals.
ZESHY_DOT_CACHE_DOCUMENTATION_DIR="${ZESHY_DOT_CACHE_DIR}/documentation"

# Directory to which Zeshy caches documentation for Zeshy-specific aliases.
ZESHY_DOT_CACHE_DOCUMENTATION_ALIAS_DIR="${ZESHY_DOT_CACHE_DOCUMENTATION_DIR}/alias"

# Directory to which Zeshy caches documentation for Zeshy-specific functions.
ZESHY_DOT_CACHE_DOCUMENTATION_FUNCTION_DIR="${ZESHY_DOT_CACHE_DOCUMENTATION_DIR}/function"

# Directory to which Zeshy caches documentation for Zeshy-specific globals.
ZESHY_DOT_CACHE_DOCUMENTATION_GLOBAL_DIR="${ZESHY_DOT_CACHE_DOCUMENTATION_DIR}/global"

# ....................{ PATHS ~ optional                   }....................
# Initramfs directory used by default by the *_initramfs*() family of functions.
# This path is safely ignorable, regardless of whether you require an initramfs
# or call such functions.
ZESHY_INITRAMFS_HOME='/usr/src/initramfs'

# ....................{ CONSTANTS                          }....................
# Maximum height of the directory stack. Once full, pushing new directories onto
# the top of the directory stack implicitly pops that number of directories off
# the bottom of the directory stack. Setting this to 0 or the empty string
# disables such behavior (i.e., permits arbitrarily large directory stacks).
ZESHY_DIR_STACK_MAX_SIZE=16

# ....................{ BOOLEANS                           }....................
# Booleans are false if set to the empty string and otherwise true.
#
# For simplicity, disable or enable booleans by commenting or uncommenting the
# lines on which they appear (e.g., prefixing such lines with "#" or deleting
# such prefix).

#FIXME: Rename to ZESHY_RELEASE_IS_DEBUGGING.

# If non-empty, enable computationally expensive developer-specific debug logic,
# including:
#
# * Recompilation of Zeshy digest's file on edits to the Zeshy codebase. For
#   Zeshy developers, such recompilation is essential to Zeshy development. For
#   Zeshy non-developers, repeatedly testing for such edits is merely wasteful.
ZESHY_RELEASE_IS_DEBUG=${ZESHY_BOOLEAN_TRUE}

# ....................{ BOOLEANS ~ alias                   }....................

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#FIXME: Actually, these are thoroughly obsolete. Stop using them everywhere and
#excise. Replace with proper granular support for "="-delimited aliases in
#configuration file "alias".
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# If non-empty, ...

# "1" if wrapping interactively run external commands (e.g., "cp", "grep", "ls")
# with corresponding Zeshy functions and "" otherwise. If enabled, Zeshy runs
# such commands with default options defined by the corresponding list below
# (e.g., wrapping interactively run "cp" commands with copy_path(), a Zeshy
# function passing "cp" the ZESHY_CP_OPTIONS list). If disabled, Zeshy runs
# such commands with no such defaults.
#
# For sanity, Zeshy never wraps core commands when run non-interactively (e.g.,
# "cp" when run from a script always executes "cp" with no such defaults).
ZESHY_IS_SUBSTITUTING_INTERACTIVE_COMMANDS=${ZESHY_BOOLEAN_TRUE}

#FIXME: Document.
ZESHY_IS_ABBREVIATING_INTERACTIVE_COMMANDS=${ZESHY_BOOLEAN_TRUE}

# ....................{ BOOLEANS ~ error                   }....................
# If non-empty, print a stack trace on either:
#
# * A Zsh alias, function, or script throwing an uncaught exception.
# * A Zsh alias, function, or script or external command returning unhandled
#   non-zero exit status.
#
# Please enable this boolean when submitting bug reports.
ZESHY_IS_ERROR_HANDLER_PRINTING_CALL_STACK=${ZESHY_BOOLEAN_TRUE}

# If non-empty, print the documentation of the Zsh function or script throwing
# such exception or calling the external command returning such non-zero exit
# status. The definition of "documentation" depends on context.
#
# Function documentation includes all "#"-prefixed lines exactly preceding such
# function definition, themselves prefixed by either a blank line or start of
# the file (optionally followed by an ignored "# ....................{"-
# prefixed banner).
#
# Script documentation includes all "#"-prefixed lines at the top of such
# script implementation, excluding shebang lines (e.g., "#!/usr/bin/env zsh").
ZESHY_IS_ERROR_HANDLER_PRINTING_DOCUMENTATION=${ZESHY_BOOLEAN_TRUE}

# If non-empty, print the source code of the Zsh function or script throwing
# such exception or calling the external command returning such non-zero exit
# status. If such function or script is sufficiently small (e.g., less than six
# lines), this prints the definition of such function or script; otherwise, this
# prints only the exact line within such function or script responsible for such
# error and several previous and subsequent lines of context about such line.
#
# Please enable this boolean when submitting bug reports.
ZESHY_IS_ERROR_HANDLER_PRINTING_SOURCE_CODE=${ZESHY_RELEASE_IS_DEBUG}
