#!/usr/bin/env zsh
# ====================[ zsh                                ]====================
#
# --------------------( SYNOPSIS                           )--------------------
# Main Zsh configuration file.

# ....................{ DECLARATIONS                       }....................
# For readability, declare global variables prior to their definition below.
integer_global_export\
    HISTSIZE\
    SAVEHIST
string_global_export HISTFILE

# ....................{ HISTORY                            }....................
# Maximum number of lines of Zsh command-line history to persist.
HISTSIZE="${HISTSIZE:-1024}"

# Maximum number of lines of Zsh command-line history to retain between logins.
SAVEHIST="${SAVEHIST:-1024}"

# File to which Zsh persists command-line history.
HISTFILE="${HISTFILE:-${ZESHY_USER_DIR}/history}"

# --------------------( WASTELANDS                         )--------------------
