#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

declare_parcel_as_script_with_stdin <<'---'
Handle *jobs* (i.e., processes owned by the current shell).
---

# --------------------( WASTELANDS                         )--------------------
#FUXME: Jobs aren't merely running processes. They're running processes managed
#by the current shell (i.e., run *AND* not disowned by such shell). This is a
#considerably more granular aspect of process control than we're managing here.
#Rename this parcel to @{process}.
