#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

declare_parcel_as_script_with_stdin <<'/---'
Declare documentation for all globals, functions, and aliases declared by the
topmost @{main} parcel.
/---

# ....................{ GLOBALS                            }....................
declare_global_with_stdin <<'/---'
string ZESHY_ZSH_VERSION_REQUIRED

Oldest `zsh` version under which `zeshy` is known to run without error.
/---

# ....................{ GLOBALS ~ exception                }....................
declare_global_with_stdin <<'/---'
string ZESHY_EXCEPTION_MESSAGE

Message associated with the most recently thrown exception. See
throw_exception() for further details.
/---

declare_global_with_stdin <<'/---'
string ZESHY_EXCEPTION_STATUS

Exit status associated with the most recently thrown exception. See
throw_exception() for further details.
/---

declare_global_with_stdin <<'/---'
list ZESHY_EXCEPTION_FUNCSTACK

Copy of canonical list global ${funcstack} at the time of the most recently
thrown exception. See throw_exception() for further details.
/---

declare_global_with_stdin <<'/---'
list ZESHY_EXCEPTION_FUNCFILETRACE

Copy of canonical list global ${funcfiletrace} at the time of the most recently
thrown exception. See throw_exception() for further details.
/---

declare_global_with_stdin <<'/---'
list ZESHY_EXCEPTION_FUNCSOURCETRACE

Copy of canonical list global ${funcsourcetrace} at the time of the most
recently thrown exception. See throw_exception() for further details.
/---

# --------------------( WASTELANDS                         )--------------------
