#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

declare_parcel_as_script_with_stdin <<'/---'
Document all globals, functions, and aliases declared by @{digest}.
/---

# ....................{ GLOBALS                            }....................

# ....................{ DIGESTERS                          }....................
declare_function_with_stdin <<'/---'
void ::digest_zeshy_compile(void)

Compile the current digest file. After doing so, coerce the modification time of
such file to the modification time of the newest path such file depends on and
autoload all functions newly compiled into such file.
/---

# ....................{ OUTPUTTERS                         }....................
declare_function_with_stdin <<'/---'
void ::output_digest_metadata(void)

Ouput metadata describing the current digest file, including the modification
times of both such file and the newest path such file depends upon. Note this
function is called only under debug builds of `zeshy`.
/---

# --------------------( WASTELANDS                         )--------------------
