#!/usr/bin/env zsh
# ====================[ float                              ]====================
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy Float, handling core floating point functionality.

# ....................{ EXCEPTIONS                         }....................
# void die_unless_float(
#   char *string, char *error_message = 'not a float')
#
# Throw an exception unless the passed string is a float.
die_unless_float() {
    die_unless_one_or_two_args\
        'expected one string and optional error message'
    is_float "${1}" or die "${2:-\"${1}\" not a float}"
}

# ....................{ TESTS                              }....................
# bool is_float(char *string)
#
# Return true if the passed string is a float (i.e., an optional negative sign,
# one or more digits, a decimal place, and one or more digits).
is_float() {
    # See is_integer() for discussion.
    die_unless_one_arg 'expected one string'
    is "${1}" == (-|)<->.<-> si
}

# ....................{ WRITERS                            }....................
# float round_float(float number, int precision = 0)
#
# Round the passed float to the passed number of decimal places (defaulting to 0
# and hence rounding to a whole integer).
round_float() {
    die_unless_one_or_two_args 'expected one float and optional precision'
    die_unless_float "${1}"
    float number="${1}"
    integer precision="${2:-0}"
    printf "%.${precision}f\n" ${number}
}

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#
# Copyright 2007-2012 by Cecil Curry.
#
#   http://www.raiazome.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
