#!/usr/bin/env zsh
# ====================[ number                             ]====================
#                     [ Time-stamp: "2009-04-18 19:29:36 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Zeshy Integer, implementing integer type-handling.

# ....................{ RANDOMIZERS                        }....................
# bool is_numeric(char *string)
#
# Return true if the passed string is numeric (i.e., settable into an integer).
is_numeric() {
    die_unless_one_argument 'expected exactly one string'
    is "${1}" == <-> si
}

# ....................{ RANDOMIZERS                        }....................
#FIXME: Add optional parameters for changing the range. Also provide a function
#based on the rand48() function imported via the above module. (Note this
#function does not exist on all systems. Fortunately, "${RANDOM}" does.)
# int get_random_integer(void)
#
# Get a random integer in the range [0, 32767].
get_random_integer() {
    die_unless_no_arguments
    print "${RANDOM}"
}

# ....................{ CONVERTERS ~ type                  }....................
# char *integer_to_comma_separated_string(int integer)
#
# Convert the passed integer to a comma-separated string: e.g.,
#     comma_separate_integer 1776  # prints 1,776
integer_to_comma_separated_string() {
    die_unless_one_argument 'expected exactly one integer'

    #FIXME: Be nice to find a pure Zsh analogue to this.
    print "${1}" | awk "{ printf \"%'d\n\", \$1 }"
}

#FIXME: Obsolete.
# For convenience, this function also accepts "stdin"-style piped input: e.g.,
#     echo 1776 | comma_separate_integer #     1,776

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyright 2007-2012 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
