#!/usr/bin/env zsh
# ====================[ theme                              ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2016 by Cecil Curry.
# See "LICENSE" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Handle Zeshy themes.

# ....................{ EXCEPTIONS                         }....................

# --------------------( WASTELANDS                         )--------------------
