#!/usr/bin/env zsh
# ====================[ rtorrent                           ]====================
#
# --------------------( SYNOPSIS                           )--------------------
# Configure "rtorrent", a command-line BitTorrent client.

# ....................{ RTORRENT                           }....................
document_global '
string ZESHY_RTORRENT_SCREEN_SESSION_NAME

"screen" session under which Zeshy runs "rtorrent".
'
ZESHY_RTORRENT_SCREEN_SESSION_NAME='rtorrent'
