#!/usr/bin/env zsh
# ====================[ escape                             ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Handle string escapes (i.e., shell-reserved characters preceded by "\").

# ....................{ ESCAPERS                           }....................
declare_function_with_stdin <<'________________<heredoc?>________________'
declare_function '
string escape_string(string text1, string text2, ...)

Escape all shell-reserved characters in the passed strings: e.g.,

.escape_string()
==========================================
[source]
------------------------------------------
>>> escape_string "(Three Rings)" "[for the]" "{Elven-kings}"
\(Three\ Rings\) \[for\ the\] \{Elven-kings\}
------------------------------------------
==========================================
________________<heredoc?>________________
function escape_string() {
    die_unless_args 'expected at least one string'
    print_string "${(q)*}"
}

declare_function_with_stdin <<'________________<heredoc?>________________'
string escape_string_double_quotes(string text1, string text2, ...)

Escape all double quotes in the passed strings: e.g.,

.escape_string_double_quotes()
==========================================
[source]
------------------------------------------
>>> escape_string_double_quotes 'I whispered, "I am too young,"'
I whispered, \"I am too young,\"
------------------------------------------
==========================================
________________<heredoc?>________________
function escape_string_double_quotes() {
    die_unless_args 'expected at least one string'
    replace_string_matches_with_string "${*}" '"' '\"'
}

# --------------------( WASTELANDS                         )--------------------
