#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

declare_parcel_as_script_with_stdin <<'-/-'
Handle *units* (i.e., strings formatted as either integers or floats suffixed by
unit specifiers).
-/-

# ....................{ EXCEPTIONS                         }....................
declare_function_with_stdin <<'/---'
void die_unless_frequency(
    string frequency,
    string error_message =
        "\"${frequency}\" not a valid frequency (e.g., 1.8Ghz)")

Throw an exception with the passed message unless the passed string is a
syntactically valid frequency. See is_frequency() for further details.
/---
function die_unless_frequency() {
    die_unless_args_1_to_2\
        'expected one frequency and optional error message'
    string frequency="${1}"
    is_frequency "${frequency}" or die\
        "${2:-\"${frequency}\" not a valid frequency (e.g., 1.8Ghz)}"
}

# ....................{ TESTERS                            }....................
#FIXME: Provide an example.
declare_function_with_stdin <<'/---'
[status: boolean] is_frequency(string frequency)

Return success if the passed string is a syntactically valid *frequency* (i.e.,
is an integer or float suffixed by either `THz`, `GHz`, `MHz`, `KHz`, or `Hz`).
/---
function is_frequency() {
    die_unless_arg 'expected one frequency'
    is_string_matches_glob "${1}" <->##('.'<->##|)([TGMK]|)'Hz'
}

# --------------------( WASTELANDS                         )--------------------
#FIXME: Shift the general-purpose "_frequency" functions below into a new
#component of the main zeshy codebase.
