#!/usr/bin/env zsh
# ====================[ zprofile                           ]====================
#                     [ Time-stamp: "2009-04-18 19:23:19 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Run after "zshenv" but before "zshrc" and "zlogin", for login shells.
#
# --------------------( VARIABLES                          )--------------------
# This script aggregates all environment variables into one file. Note that many
# distros dis-aggregate such environment variables into separate files under
# "/etc/env.d/", which they then programmatically aggregate into a composite
# "/etc/profile.env" file, which this script then sources. Since this tends to
# make for a rather clumsy and overly abstract means of defining environment
# variables, Zeshy prefers to "simply" clump such variables together, here.

# ....................{ PREAMBLE                           }....................
# Absolute path of Zeshy's topmost directory.
[[ -n "${ZESHY_HOME-}" ]] || export ZESHY_HOME="${0:h}/../.."(:A)

# Initialize Zeshy.
[[ $(whence -w get_zeshy_version) == *': function' ]] ||
    source "${ZESHY_HOME}/src/init/main"

# Establish default profile settings.
set_profile_defaults

#FIXME: Obsolete.
#[[ -n "${ZESHY_HOME-}" ]] ||
#    export ZESHY_HOME="$(readlink -e "${0:h}/../..")"

# Absolute path of the current script.
#local zprofile_path="$(readlink -e "${0}")"

# Absolute path of Zeshy's topmost directory.
#[[ -n "${ZESHY_HOME-}" ]] ||
#    export ZESHY_HOME="$(readlink -e "$(dirname "${zprofile_path}")/../..")"

# Initialize Zeshy. Note that "source zeshy" is insufficient on the first
# logon. Hence, our usage of an absolute path for safety here.

# Inform the user that this script is being imported.
#utter "loading \"${zprofile_path}\"..."

#           if is_nonempty "${PATH}"
#           then PATH+=":${dirname}"
#           else PATH="${dirname}"
#           fi
#
#is_set 'EDITOR' or global_string EDITOR=$(which_binaries_nonfatal emacs vim nano ed)
#is_set 'PAGER'  or global_string PAGER=$(which_binaries_nonfatal less more)
#zimport zeshy/type/integer
#zimport zeshy/os

#FIXME: Only do so if Firefox is installed. Actually, this probably no longer
#matters, does it? (It's been just a few years...)
# Disable Firefox's Pango-enabled font antialiasing on low-end machines.
#export MOZ_DISABLE_PANGO=$(one_if is $(get_memory_total) -ge GB si)

# Lastly, export munged paths into our caller's shell environment.
#export MANPATH INFOPATH

#FIXME: Hmm; and what, prey tell, is this?
#export XUSERFILESEARCHPATH="${XAPPLRESDIR}/%N"
#make_directory_if_not_found "${XAPPLRESDIR}" "${XUSERFILESEARCHPATH}"

#!/bin/zsh
# ....................{ PREAMBLE                           }....................
# Absolute path to the current script.
#local zprofile_path="$(readlink --canonicalize-existing "${0}")"

# Directory having the current script.
#[[ -n "${ZESHY_HOME}" ]] ||
#    export ZESHY_HOME=$(readlink --canonicalize-existing "$(dirname "${zprofile_path}")/..")

# Import Zeshy Core.
#if [[ $(whence -w zimport) =~ ': function' ]]
#then zimport zeshy/core
#else source "${ZESHY_HOME}/src/zeshy/core"
#fi

# Inform the user that this script is being imported.
#utter_import "${zprofile_path}"

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyright 2007-2012 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
