#!/usr/bin/env zsh
# ====================[ file                               ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2012 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Define file-specific aliases.

# ....................{ GLOBALS                            }....................
# Standard POSIX file descriptors.
integer_constant_global_export\
    ZESHY_FILE_DESCRIPTOR_STANDARD_INPUT=0\
    ZESHY_FILE_DESCRIPTOR_STANDARD_OUTPUT=1\
    ZESHY_FILE_DESCRIPTOR_STANDARD_ERROR=2

# ....................{ CLOSERS                            }....................
# void close_standard_input(void)
#
# Close the standard input file descriptor (0) and named pipe ("/dev/stdin").
alias close_standard_input="exec ${ZESHY_FILE_DESCRIPTOR_STANDARD_INPUT}<&-"

# void close_standard_output(void)
#
# Close the standard print_string file descriptor (1) and named pipe ("/dev/stdout").
alias close_standard_output="exec ${ZESHY_FILE_DESCRIPTOR_STANDARD_OUTPUT}>&-"

# void close_standard_error(void)
#
# Close the standard error file descriptor (2) and named pipe ("/dev/stderr").
alias close_standard_error="exec ${ZESHY_FILE_DESCRIPTOR_STANDARD_ERROR}>&-"

# ....................{ RUNNERS                            }....................
# string run_with_piped_input(
#   string command_name, string command_arg1, string command_arg2, ...)
#
# Run the passed command by piping the standard input piped to the current
# function or script to such command. Typically, this alias is used in concert
# with the is_standard_input_piped() function to propagate piped input: e.g.,
#
#     >>> salvia() {
#     ...     is_standard_input_piped and run_with_piped_input cat or print_string "${@}" cat
#     ... }
#     >>> print  divinorum | salvia
#     divinorum
#     >>> salvia divinorum
#     divinorum
alias run_with_piped_input='{
    cat /dev/stdin;
    close_standard_input
} |'

# --------------------( WASTELANDS                         )--------------------
