#!/usr/bin/env zsh

:parcel <<'/---'
Configure `zeshy`-specific `startx` functionality.
/---

# ....................{ PATHS                              }....................
#FIXME: Rename to ${ZY_STARTX_LOG_FILENAME}.
:str.global\
    ZY_X_LOG_FILENAME="${HOME}/.xsession" <<'/---'
Absolute path of the file to which :x(), the `zeshy`-specific `startx` wrapper,
logs standard output and error.
/---
