#!/usr/bin/env zsh

declare_parcel_as_script_with_stdin <<'/---'
Configure `zeshy`-specific `startx` functionality.
/---

# ....................{ PATHS                              }....................
#FIXME: Rename to ${ZESHY_STARTX_LOG_FILENAME}.
:string_global\
    ZESHY_X_LOG_FILENAME="${HOME}/.xsession" <<'/---'
Absolute path of the file to which :x(), the `zeshy`-specific `startx` wrapper,
logs standard output and error.
/---
