#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2014 by Cecil Curry.
# See "COPYING" for additional details.

:parcel <<'/---'
Handle *process* (i.e., currently running commands) aliases.
/---

# --------------------( WASTELANDS                         )--------------------
# ....................{ SETTERS                            }....................
#FUXME: Convert to a function. No viable reason to define this as an alias.
#:alias_command\
#    'void set_integer_to_pid_job_prior(string integer_name)'\
#    '{ :int.set "$(:stdin.get)" "${!}" } <<<' <<'/---'
#Set the passed integer to the process identifier (PID) of the most recently
#backgrounded command. This includes commands appended by `&`, commands prefixed
#by `bg`, and the coprocess of the current shell.
#/---
