#!/usr/bin/env zsh

:parcel <<'/---'
Configure `zeshy`-specific `git` functionality.
/---

# ....................{ ALIASES                            }....................
# See "00-core/alias" for further details.
#
# Note the following git-specific nomenclature:
#
# * "master" is the local master branch.
# * "origin master" is the remote master branch (i.e., branch "master" on the
#   remote repository symbolically referred to as "origin").
# * "origin/master" is the local master tracking branch (i.e., the local
#   copy of "origin master" and hence tracking such remote branch).

ZESHY_ALIAS_CLI_ABBREVIATIONS+=(
    {gitcl}one  'git clone'
    {gitd}iff   'git diff'
    {gitp}u{l}l 'git pull'
    {gitp}u{s}h 'git push'
    {gits}tatus 'git status'

    # ==================[ ADD                               ]==================
    {gita}dd      'git add'
    {gita}dd{a}ll 'git add --all'

    # ==================[ BRANCH                            ]==================
    # Switch to the passed branch.
    {gitb}ranch 'git checkout'

    # Switch to the local master branch.
    {gitb}ranch{m}aster 'git checkout master'

    # Create the passed branch, remaining on the current branch.
    {gitb}ranch{c}reate 'git branch'

    # Create and switch to the passed branch.
    {gitb}ranch{c}reate{s}witch 'git checkout -b'

    #FIXME: This should definitely require interactive zeshy confirmation and
    #hence a new function.

    # Delete the passed branch.
    {gitb}ranch{d}elete 'git branch -D'

    # ==================[ COMMIT                            ]==================
    {gitc}ommit             'git commit'
    {gitc}ommit{a}ll        'git commit --all'
    {gitc}ommit{a}ll{a}mend 'git commit --all --amend'

    #FIXME: This should definitely require interactive zeshy confirmation and
    #hence a new function.

    # Uncommit the prior commit, preserving both the working tree and index.
    {gitc}ommit{u}ndo 'git reset --soft HEAD~1'

    # ==================[ CONFIGURE                         ]==================
    {git}con{f}ig               'git config'
    {git}con{f}ig{l}ist         'git config --list'
    {git}con{f}ig{s}ystem       'git config --system'
    {git}con{f}ig{s}ystem{l}ist 'git config --system --list'
    {git}con{f}ig{u}ser         'git config --global'
    {git}con{f}ig{u}ser{l}ist   'git config --global --list'

    # ==================[ GREP                              ]==================
    {gitg}rep       ':grep_git_with_options'
    {gitg}rep{r}oot ':grep_git_root_with_options'

    # ==================[ INDEX                             ]==================
    # Unstage all passed files from the index.
    {giti}ndex{u}ndo 'git reset HEAD'

    # ==================[ LOG                               ]==================
    {gitl}og        'git log'
    {gitl}og{g}raph 'git log --graph --decorate --abbrev-commit --pretty=oneline'

    # ==================[ MERGE                             ]==================
    {gitm}erge         'git merge'

    # ==================[ REBASE                            ]==================
    # Automatically rebase the current branch to the passed branch, thus moving
    # the HEAD of the former to the HEAD of the latter.
    {gitr}ebase 'git rebase'

    {gitr}ebase{c}ontinue    'git rebase --continue'
    {gitr}ebase{i}nteractive 'git rebase --interactive'

    # Automatically rebase the current branch to the remote master (e.g., to
    # eliminate extraneous "Merged from..." commits implicitly produced by
    # unconflicting merges.)
    {gitr}ebase{o}rigin{m}aster 'git rebase origin/master'

    # Interactively rebase the current branch to the local master, permitting
    # all new commits in the former since the last push to the latter to be
    # selectively reordered and/or squashed. After doing so, such commits may
    # be moved to the master with the following workflow:
    #
    #     # Switch to the desired branch.
    #     >>> gitb existingbranch
    #     # Interactively rebase such branch to the local master.
    #     >>> gitrim
    #     # Switch to the local master.
    #     >>> gitbm
    #     # Move the HEAD of the local master to the HEAD of such branch.
    #     >>> gitr existingbranch
    {gitr}ebase{i}nteractive{m}aster 'git rebase --interactive master'

    # Interactively rebase the local master to the remote master, permitting all
    # new commits in the former since the last push to the latter to be
    # selectively reordered and/or squashed.
    {gitr}ebase{i}nteractive{o}rigin{m}aster
        'git rebase --interactive origin/master'

    # ==================[ RESET                             ]==================

    #FIXME: Wrap with a function requiring the user interactively confirm such
    #reset.

    # Reset. Before calling such alias, *ALWAYS* commit all uncommitted changes
    # *AND* store all commits to be purged by such reset into a branch (either
    # existing or newly created for the purpose of storing such commits). That
    # is to say, consider a workflow resembling:
    #
    # * If storing such commits in a new branch, simply create such branch.
    #   Since branches are simply commit pointers, this preserves a pointer to
    #   the current commit and hence all prior commits to "master": e.g.,
    #
    #    # Create the temporary branch but remain in "master".
    #    >>> gitbc newbranch
    #    # Either reset to the remote origin or...
    #    >>> gitresho
    #    # ...manually purge prior commits. (Here, the prior three commits.)
    #    >>> gitresh HEAD~3
    #    # Switch to such branch.
    #    >>> gitb newbranch
    #
    # * Else, such commits must be manually merged into an existing branch:
    #   e.g.,
    #
    #    # Switch to such branch.
    #    >>> gitb existingbranch
    #    # Merge all commits from "master" into such branch.
    #    >>> gitm master
    #    # Switch back to "master".
    #    >>> gitbm
    #
    #    # Either reset to the remote origin or purge prior commits, as above.
    #    >>> gitresho        # Either this...
    #    >>> gitresh HEAD~3  # ...or this.
    #
    #    # Return to such branch.
    #    >>> gitb existingbranch
    {gitres}et{h}ard         'git reset --hard'
    {gitres}et{h}ard{o}rigin 'git reset --hard origin/master'

    # ==================[ STASH                             ]==================
    # Since git implicitly merges all uncommitted changes to the current
    # working tree when switching branches, stash changes *BEFORE* switching
    # branches to prevent changes from "leaking" between branches.

    # Stash all uncommitted changes and revert to the current branch's most
    # recent commit (i.e., "HEAD").
    {git}s{t}ash         'git stash'

    # List all prior stashes.
    {git}s{t}ash{l}ist   'git stash list'

    # Merge all uncommitted changes in the passed stashed (defaulting to the
    # most recent stash) into the current working tree.
    {git}s{t}ash{a}pply  'git stash apply'

    # Merge as above *AND* remove such stash from the stash list.
    {git}s{t}ash{a}pply{d}elete 'git stash pop'

    # Remove the passed stash from the stash list.
    {git}s{t}ash{d}elete 'git stash drop'

    # Create a new branch with the passed name, check out the most recent
    # commit from the branch from which the passed stash (defaulting to the
    # most recent stash) was originally stashed into the new branch, merge all
    # uncommited changes from such stash into the new branch, and remove such
    # stash if such changes merged successfully.
    {git}s{t}ash{b}ranch 'git stash branch'
)

# ....................{ OPTIONS                            }....................
:list_global ZESHY_OPTIONS_GIT_GREP <<'/---'
`git grep` options for `zeshy`-specific greppers (e.g., :grep_git()).
/---
ZESHY_OPTIONS_GIT_GREP=(
    -I
    --perl-regexp
)

:list_global ZESHY_OPTIONS_GIT_GREP_IF_INTERACTIVE <<'/---'
`git grep` options when run interactively.
/---
ZESHY_OPTIONS_GIT_GREP_IF_INTERACTIVE=(
    --break
    --color=always
    --heading
    --line-number

    # Uncomment to print one line of context both above and below matched lines.
    #--context 1
)

:list_global ZESHY_OPTIONS_GIT_GREP_IF_NONINTERACTIVE <<'/---'
`git grep` options when run non-interactively.
/---
ZESHY_OPTIONS_GIT_GREP_IF_NONINTERACTIVE=(
    --color=never
)
