#!/usr/bin/env zsh

declare_parcel_as_script_with_stdin <<'/---'
Configure `zeshy`-specific `git` functionality.
/---

# ....................{ ALIASES                            }....................
# See "00-core/alias" for further details.

ZESHY_ALIAS_CLI_ABBREVIATIONS+=(
    # Basic actions.
    {gitcl}one  'git clone'
    {gitd}iff   'git diff'
    {gitl}og    'git log'
    {gitp}u{l}l 'git pull'
    {gitp}u{s}h 'git push'
    {gits}tatus 'git status'

    # Add.
    {gita}dd      'git add'
    {gita}dd{a}ll 'git add --all'

    # Commit.
    {gitc}ommit             'git commit'
    {gitc}ommit{a}ll        'git commit --all'
    {gitc}ommit{a}ll{a}mend 'git commit --all --amend'

    # Grep.
    {gitg}rep       'grep_git_repository_from_dir_current:'
    {gitg}rep{r}oot 'grep_git_repository_from_dir_root:'

    # Rebase.
    {gitr}ebase{c}ontinue    'git rebase --continue'
    {gitr}ebase{i}nteractive 'git rebase --interactive'

    # Correct "Merged from..." commits implicitly produced by non-conflicting
    # merges. (Rather useful.)
    {gitr}ebase{o}rigin 'git rebase origin'

    # Interactively rebase all commits committed since the last push to the remote
    # repository. (This is the common case.)
    {gitr}ebase{i}nteractive{o}rigin 'git rebase --interactive'
)
