#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

declare_parcel_as_script_with_stdin <<'/---'
Document all globals, functions, and aliases declared by @{*-test/runnable}.
/---

# ....................{ EXCEPTIONS                         }....................
:func.document <<'/---'
:void :func.die_if(:string func_name1, ...)

Throw an exception if any passed function exists. See :func.is() for further
details.
/---

:func.document <<'/---'
:void :func.die_unless(:string func_name1, ...)

Throw an exception unless all passed functions exist. See :func.is() for
further details.
/---

# ....................{ TESTERS                            }....................
:func.document <<'/---'
[status = :bool] :func.is(:string func_name1, ...)

Report success if all passed functions exist.
/---

# --------------------( WASTELANDS                         )--------------------
