#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

:parcel <<'/---'
Handle `pv`, the CLI pipe viewer for visualizing command progress.
/---

# ....................{ PRINTERS                           }....................
declare_function_with_stdin <<'/---'
[stderr: string, status: integer] view_pipe_progress()

Visualize the progress of the current pipeline with a progress bar with the
currently configured `pv`-specific options (e.g., ${ZESHY_OPTIONS_PV}) to
standard error, to avoid conflict with standard output both connecting pipeline
commands and printed by `ncurses`-based commands. Assuming default options, such
progress includes such pipeline's total elapsed time and predicted remaining
time until termination.
/---
function view_pipe_progress() {
    die_if_args
    run_command_with_options_configured 'command pv'\
        'ZESHY_OPTIONS_PV ZESHY_OPTIONS_PV_IF_PRINTING_PROGRESS_BAR'
}

# --------------------( WASTELANDS                         )--------------------
