#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

declare_parcel_as_script_with_stdin <<'/---'
Handle core string constants.
/---

# ....................{ GLOBALS                            }....................
:string_global ZESHY_IFS_DEFAULT=$' \t\n\0' <<'/---'
Default internal field separator (IFS) for splitting fields on longest
contiguous substrings of *whitespace* (i.e., space, tab, newline, and null
characters). By POSIX design, setting string global ${IFS} to this default is
equivalent to unsetting such global.
/---

# --------------------( WASTELANDS                         )--------------------
