#!/usr/bin/env zsh
# ====================[ rtorrent                           ]====================
#
# --------------------( SYNOPSIS                           )--------------------
# User-specific Zeshy "rtorrent" configuration.

# ....................{ USERS                              }....................
# User under which to run "rtorrent".
global_string ZESHY_RTORRENT_USERNAME='root'

# Screen session under which to run "rtorrent" under such user.
global_string ZESHY_RTORRENT_SCREEN_SESSION='rtorrent'
