#!/usr/bin/env zsh
# ====================[ rtorrent                           ]====================
#
# --------------------( SYNOPSIS                           )--------------------
# User-specific Zeshy "rtorrent" configuration.

# ....................{ USERS                              }....................
# User running "rtorrent". Ideally, this is the user intending to
# foreground and actually use rtorrent.
global_string ZESHY_RTORRENT_USER='root'

# Screen session under which rtorrent is to be run.
global_string ZESHY_RTORRENT_SCREEN_SESSION='rtorrent'

# ....................{ PATHS                              }....................
# Absolute path of the file persisting the running "rtorrent" process ID (PID).
#FIXME: This looks good. But we need to implement it, first! Which means,
#transitively, we need a die_unless_user() function. Here's the trivial
#awk-based implementation:
#
#  awk -F":" '{ print $1 }' /etc/passwd
#
#Of course, we then need a get_users_file() function. And then, since we'd
#rather implement a pure-Zsh solution, we'd like to implement a function:
#
#string split_columns_from_lines(string text, string column_separator)
#
#I'm pretty sure we can implement this by splitting text into a list of lines
#and running a single parameter expansion on such list (possibly also locally
#setting "IFS=':'"), which Zsh *SHOULD* apply to each list member. If we can't
#do this and instead have... 

#global_string ZESHY_RTORRENT_PID_FILE="$(get_pid_file "${ZESHY_RTORRENT_USER}" rtorrent)"

#if is "${RTORRENT_USER}" == root si
#then ZESHY_RTORRENT_PIDFILE="/var/run/rtorrent.pid"
#else ZESHY_RTORRENT_PIDFILE="/home/${RTORRENT_USER}/.rtorrent.pid"
#fi
