#!/usr/bin/env zsh
# ====================[ path                               ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Handle Zeshy-specific paths.

# ....................{ PATHS                              }....................
# Such paths depend on command-line option "--zeshy-dot-dir" and hence cannot be
# defined until having matched such option (e.g., zeshy startup).

declare_global_with_stdin <<'________________<heredoc?>________________'
string ZESHY_USER_PID_DIR

Absolute path of the directory caching `zeshy`-managed process IDs. If the
current user has superuser privileges, this is a canonical system-wide directory
if such directory exists (e.g., `/run`, `/var/run`); else, this is a user-
specific subdirectory of `zeshy`\'s dot directory.
________________<heredoc?>________________

# ....................{ PATHS ~ completion                 }....................
declare_global_with_stdin <<'________________<heredoc?>________________'
string ZESHY_USER_COMPLETION_STARTUP_FILE

Absolute path of the file caching compinit() completion initialization.
________________<heredoc?>________________

declare_global_with_stdin <<'________________<heredoc?>________________'
string ZESHY_USER_COMPLETION_RESULTS_DIR

Absolute path of the directory caching `zsh` completion results.
________________<heredoc?>________________

# ....................{ PATHS ~ documentation              }....................
declare_global_with_stdin <<'________________<heredoc?>________________'
string ZESHY_USER_HELP_DIR

Absolute path of the directory caching `zeshy` documentation.
________________<heredoc?>________________

declare_global_with_stdin <<'________________<heredoc?>________________'
string ZESHY_USER_HELP_ALIAS_DIR

Absolute path of the directory caching `zeshy`-specific alias documentation.
________________<heredoc?>________________

declare_global_with_stdin <<'________________<heredoc?>________________'
string ZESHY_USER_HELP_FUNCTION_DIR

Absolute path of the directory caching `zeshy`-specific function documentation.
________________<heredoc?>________________

declare_global_with_stdin <<'________________<heredoc?>________________'
string ZESHY_USER_HELP_GLOBAL_DIR

Absolute path of the directory caching `zeshy`-specific global documentation.
________________<heredoc?>________________

# ....................{ PATHS ~ zsh                        }....................
declare_global_with_stdin <<'________________<heredoc?>________________'
string ZESHY_USER_DIR_STACK_FILE

Absolute path of the file persisting `zsh` directory stack directories.
________________<heredoc?>________________

declare_global_with_stdin <<'________________<heredoc?>________________'
string HISTFILE

Absolute path of the file persisting `zsh` command-line history.
________________<heredoc?>________________

# ....................{ GETTERS                            }....................
run_hook_on_zeshy_startup startup_zeshy_paths

declare_function_with_stdin <<'________________<heredoc?>________________'
void startup_zeshy_paths(void)

Define `zeshy`-specific paths. Such paths depend on string global
${ZESHY_USER_CACHE_DIR} itself depending on optional command-line option
`--zeshy-dot-dir`. Hence, such paths must be defined on each `zeshy` startup
rather than statically precompiled into `zeshy`\'s user digest file.
________________<heredoc?>________________
function startup_zeshy_paths() {
    # Validate sanity. If ignoring zeshy's dot directory, return silently.
    die_if_args
    is_string_nonempty "${ZESHY_DOT_DIR}" or return_true

    # Set such paths, having now matched command-line option "--zeshy-dot-dir"
    # and hence string global ${ZESHY_USER_CACHE_DIR}.
    ZESHY_USER_COMPLETION_STARTUP_FILE="${ZESHY_USER_CACHE_DIR}/completion_startup"
    ZESHY_USER_COMPLETION_RESULTS_DIR="${ZESHY_USER_CACHE_DIR}/completion_results"
    ZESHY_USER_DIR_STACK_FILE="${ZESHY_USER_CACHE_DIR}/dir_stack"
    HISTFILE="${ZESHY_USER_CACHE_DIR}/history"
    ZESHY_USER_HELP_DIR="${ZESHY_USER_CACHE_DIR}/help"
    ZESHY_USER_HELP_ALIAS_DIR="${ZESHY_USER_HELP_DIR}/alias"
    ZESHY_USER_HELP_FUNCTION_DIR="${ZESHY_USER_HELP_DIR}/function"
    ZESHY_USER_HELP_GLOBAL_DIR="${ZESHY_USER_HELP_DIR}/global"

    # See ${ZESHY_USER_PID_DIR} documentation for further details.
    if { is_superuser } {
        ZESHY_USER_PID_DIR="$(get_dir_writable_first_if_found /run /var/run)" or
        ZESHY_USER_PID_DIR="${ZESHY_USER_CACHE_DIR}/pid"
    } else {
        ZESHY_USER_PID_DIR="${ZESHY_USER_CACHE_DIR}/pid"
    }

    # Create all non-extant directories not managed elsewhere. Note "zeshy/help"
    # components manage all help documentation directories.
    make_dir_if_not_found\
        "${ZESHY_USER_COMPLETION_RESULTS_DIR}"\
        "${ZESHY_USER_PID_DIR}"

    #FIXME: Obviously, should be rewritten on upgrades. I believe we intend on
    #testing for that somewhere, yes? Wherever we end up doing that, this line
    #of code should obviously be shifted to such process.

    # Cache the currently installed version of Zeshy if not already cached.
    is_file "${ZESHY_USER_VERSION_FILE}" or
        get_zeshy_version > "${ZESHY_USER_VERSION_FILE}"
}

# --------------------( WASTELANDS                         )--------------------
    #FUXME: Either shift somewhere more appropriate or rename this function to
    #something more appropriate. It's pretty much just a grab-bag of
    #miscellaneous startup code, at the moment.

#FUXME: Since the dot directory can be changed from the command-line, this
#probably isn't quite right. Indeed, this should really be pushed out of this
#file and into the Zeshy codebase. (Unsure quite where, of course...)
