#!/usr/bin/env zsh
# ====================[ X                                  ]====================
#
# --------------------( SYNOPSIS                           )--------------------
# Configure Zeshy-specific X11 behavior.

# ....................{ PATHS                              }....................
declare_global '
string ZESHY_X_LOG_FILENAME

Absolute path of the file to which start_x() logs standard output and error.
'
ZESHY_X_LOG_FILENAME="${HOME}/.xsession"

# ....................{ ALIASES                            }....................
# See "00-alias" for further details.
ZESHY_CLI_ABBREVIATIONS+=(
    {l}s{xf}ont 'print_x_fonts'
)
ZESHY_CLI_SUBSTITUTIONS+=(
    {s}tart{x} 'start_x'
)
