#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2014 by Cecil Curry.
# See "COPYING" for additional details.

:parcel <<'---'
Handle *cronjobs* (i.e., processes running under a `cron` process).
---

# ....................{ TESTERS                            }....................
#FIXME: This is *HORRIBLY* Linux-specific. It's also a bit broken. Reduce to
#pure zeshy functions.
declare_function_with_stdin <<'/---'
[status: boolean] is_cronjob()

Return success if the current process is the grandchild of a "cron" process.
/---
function is_cronjob() {
    # Validate sanity.
    die_if_args
    string cron_pids
    integer grandparent_pid

    # Return success if and only if the following conditions hold:
    #
    # * At least one process is currently running a "cron" derivative (e.g.,
    #   "fcron", "vcron").
    # * The PID of the grandparent of the current process (i.e., the parent of
    #   the parent of such process) is the PID of such a "cron" process.
    cron_pids="$(command pgrep -x cron)" and
        :is_string_matches_glob_grouped\
            "$(command ps -eo ppid,pid=)" (<->)*" ${PPID}" and
        is_string_line "${cron_pids}" "${match[1]}"
#   print "cron_pids: ${cron_pids}; gpid: ${grandparent_pid}"
}

# --------------------( WASTELANDS                         )--------------------
    # Do this prior to saying imports, as the say() function requires this.
    #FUXME: This throws an exception if "cron" is not currently running, which
    #is horrible. If "cron" is not currently running, we should return failure!

#   grandparent_pid="$(command ps -eo ppid,pid= | command grep " ${PPID}$" | command awk '{print $1}')"
#   ZESHY_IS_CRONJOB="$(one_if match_multiline "^${cron_pids}$" "${grandparent_pid}")"

    #FUXME: This no longer works, of course. That said, let's pursue the
    #familiar strategy of testing such global boolean if set and otherwise
    #caching such global boolean for subsequent lookup.
#   :is_var_nonempty ZESHY_IS_CRONJOB
#FUXME: Reimplement me! Dredge up the implementation from the WASTELANDS.
