#!/usr/bin/env zsh

:parcel <<'-/-'
Configure `zeshy`-specific `shntool` functionality.
-/-

# ....................{ OPTIONS                            }....................
:list.global ZY_OPTIONS_SHNTOOL <<'/---'
`zeshy`-specific `shntool` options (e.g., for split_file_audio_lossless()).
/---
ZY_OPTIONS_SHNTOOL=()

:list.global ZY_OPTIONS_SHNTOOL_IF_INTERACTIVE <<'/---'
`zeshy`-specific `shntool` options when run from the interactive command line.
/---
ZY_OPTIONS_SHNTOOL_IF_INTERACTIVE=(
    -P face
)

:list.global ZY_OPTIONS_SHNTOOL_IF_NONINTERACTIVE <<'/---'
`zeshy`-specific `shntool` options when run from non-interactive scripts.
/---
ZY_OPTIONS_SHNTOOL_IF_NONINTERACTIVE=(
    -q
    -O never  # never overwrite existing files when run non-interactively
)
