#!/usr/bin/env zsh
# ====================[ config                             ]====================
# User-specific Zeshy configuration.

# Command-line theme. Choices include:
#
# * "gwydden", the default Zeshy theme. (A commendably astute choice, kind Sir.)
ZESHY_THEME=gwydden

# Developer-specific boolean, "1" if this Zeshy installation is under
# development and "" otherwise. Enabling this boolean enables computationally
# expensive tests (e.g., digest synchronization, code profiling).
ZESHY_IS_DEVELOPMENT=

# ....................{ GREP                               }....................
# grep*()-specific "grep" options enabled .
#
# Do not define "GREP_OPTION"! When defined, all invocations of grep use these
# options. However, most such invocations do not expect grep to emit line
# numbers, colors, or other colorful noise. They expect grep -- plain grep, no
# ornamentation. (Let us avoid breaking the entire system, shall we?)
ZESHY_GREP_OPTIONS=(
    '--exclude-dir=.(cvs|git|hg|svn)'
    --extended-regexp
#   --no-messages
)

ZESHY_GREP_OPTIONS_IF_INTERACTIVE=(
    "${ZESHY_GREP_OPTIONS[@]}"
    --color=always
    --line-number
    --with-filename
)

# ....................{ MYSQL                              }....................
# mysql_shell()-specific MySQL shell options.
ZESHY_MYSQL_SHELL_OPTIONS=(
    --pager=less
    --auto-rehash
    --column-names
    --compress
    --ignore-case
    --line-numbers
    --named-commands
    --no-beep
    --password
    --reconnect
    --secure-auth
    --show-warnings
    --sigint-ignore
    --skip-comments
    --table
)

# ....................{ RSYNC                              }....................
# rsync_safely()-specific rsync options.
#
# The defaults, here, are probably fine. If you don't want local changes to be
# auto-overwritten by remote changes (...you probably do, but who are we to
# carp and complain), remove the '--delete' and '--delete-after' options.
ZESHY_RSYNC_OPTIONS=(
    --compress
    --cvs-exclude
    --delete --delete-after
    --devices --specials
    --human-readable
    --links --keep-dirlinks --safe-links
    --recursive
    --sparse
    --super
    --timeout=32
    --times #--no-perms --no-owner --no-group
)

# Additional rsync_safely()-specific rsync options when run interactively.
ZESHY_RSYNC_OPTIONS_IF_INTERACTIVE=(
    "${ZESHY_RSYNC_OPTIONS[@]}"
    --progress
    --verbose --verbose
)

# Additional rsync_safely()-specific rsync options when not run interactively
# (e.g., precautions against silently catastrophic, large-scale deletion).
ZESHY_RSYNC_OPTIONS_IF_NOT_INTERACTIVE=(
    "${ZESHY_RSYNC_OPTIONS[@]}"
    --max-delete=128
    --quiet
)
