#!/usr/bin/env zsh

declare_parcel_as_script_with_stdin <<'/---'
Configure core `zsh` settings.
/---

# ....................{ DIRSTACK                           }....................
declare_global_with_stdin integer DIRSTACKSIZE=16 <<'/---'
Maximum directory stack height. Once full, pushing new directories onto the
directory stack implicitly pops that number of directories off the end of the
directory stack. Setting this to 0 or the empty string disables such behavior
(i.e., permits arbitrarily large directory stacks).
/---

# ....................{ HISTORY                            }....................
declare_global_with_stdin integer HISTSIZE=1048576 <<'/---'
Maximum number of history lines to persist to ${HISTFILE}.
/---

declare_global_with_stdin integer SAVEHIST="${HISTSIZE}" <<'/---'
Maximum number of history lines to retain between logins.
/---
