#!/usr/bin/env zsh

:parcel <<'/---'
Configure core `zsh` settings.
/---

# ....................{ DIRSTACK                           }....................
:int_global DIRSTACKSIZE=16 <<'/---'
Maximum directory stack height. Once full, pushing new directories onto the
directory stack implicitly pops that number of directories off the end of the
directory stack. Setting this to 0 or the empty string disables such behavior
(i.e., permits arbitrarily large directory stacks).
/---

# ....................{ HISTORY                            }....................
:int_global HISTSIZE=1048576 <<'/---'
Maximum number of history lines to persist to ${HISTFILE}.
/---

:int_global SAVEHIST="${HISTSIZE}" <<'/---'
Maximum number of history lines to retain between logins.
/---
