#!/usr/bin/env zsh
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2013 by Cecil Curry.
# See "COPYING" for additional details.

declare_parcel_as_script_with_stdin <<'/---'
Handle *`zsh` module* aliases.
/---

# ....................{ LOADERS                            }....................
#FIXME: Convert to split aliases.
#FIXME: Add examples. Essential here, due to the complexity.

:declare_alias_simple 'void :load_module_mapfile_start(void)'\
    ':load_module_mapfile
    :try {' <<'/---'
Load `zsh` module `mapfile`, preceding :load_module_mapfile_stop() in the same
syntactic block guaranteeably unloading such module. If this alias is _not_
preceded by :load_module_mapfile_stop() in the same syntactic block, an
inscrutable `zsh` parse error will be raised. See :load_module_mapfile() for
further details.
/---

:declare_alias_simple 'void :load_module_mapfile_stop(void)'\
    '} always ={
        :unload_module_mapfile
    }=' <<'/---'
Unload `zsh` module `mapfile`, following :load_module_mapfile_start() in the
same syntactic block loading such module. This alias guarantees such module to
be unloaded, even in the event of fatal errors or thrown exceptions. See
:unload_module_mapfile() and :load_module_mapfile_start() for further details.
/---

# --------------------( WASTELANDS                         )--------------------
#f another command fails or throws an exception between that and this expansion.
