#!/usr/bin/env zsh
# ====================[ dpms                               ]====================
#
# --------------------( LICENSE                            )--------------------
# Copyright 2007-2012 by Cecil Curry.
# See "COPYING" for additional details.
#
# --------------------( SYNOPSIS                           )--------------------
# Handle X11 Display Power Management Signaling (DPMS).

# ....................{ PRINTERS                           }....................
# string print_x_dpms_info(void)
#
# Print a human-readable synopsis of current X11 DPMS settings.
function print_x_dpms_info() {
    die_if_args
    interactively say 'displaying X11 DPMS settings...'
    _print_x_dpms_info
}

function _print_x_dpms_info() {
    die_if_args
    string xset_output="$(xset -q)"
    print "${xset_output}" | grep '^Screen Saver:$'       --after-context=2
    print "${xset_output}" | grep '^DPMS (Energy Star):$' --after-context=2
}

# ....................{ SETTERS                            }....................
# void disable_x_dpms(void)
#
# Disable screen blanking (i.e., DPMS-managed monitor shutdown on inactivity).
# This is particularly helpful while enjoying media but should be manually re-
# enabled when done.
function disable_x_dpms() {
    die_if_args
    interactively say 'disabling X11 DPMS...'
    xset s off
    xset -dpms
    print_x_dpms_info
}

# void enable_x_dpms(void)
#
# Enable screen blanking (i.e., DPMS-managed monitor shutdown on inactivity).
function enable_x_dpms() {
    die_if_args
    interactively say 'enabling X11 DPMS...'
    xset s on
    xset +dpms
    print_x_dpms_info
}

# --------------------( WASTELANDS                         )--------------------
